import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {applyMasterSuite,inspectMasterSuite,suiteComparison} from '../lib/master-suite';
import {validateState,defaultMaterial,type State,type Piece,type Floor} from '../lib/model';
import {augmentState} from '../lib/project-model';
import {computeScene,pointInMulti,anchorPoint,multiArea,intersection,pieceShapes,bbox,toLocal} from '../lib/geometry';
import {analyzeRoutes} from '../lib/routes';
import {patchGroupedPiece} from '../lib/scene-edit';
import {spatialVolumes} from '../lib/brief-export';

const floor=(id:string):Floor=>({id,name:id,outline:[[0,0],[12100,0],[12100,8500],[0,8500]],originalOutline:[[0,0],[12100,0],[12100,8500],[0,8500]],pieces:[],rooms:[],source:'synthetic integration fixture',note:''});
const part=(id:string,type:Piece['type'],x:number,y:number,w:number,h:number):Piece=>({id,name:id,type,x,y,w,h,rotation:0});
const synthetic:State={version:2,floors:[floor('f1'),floor('f2')],materials:{f1:{...defaultMaterial},f2:{...defaultMaterial}},warnings:[]};
synthetic.floors[1].pieces=[part('f2-wall-06','wall',3210,99,198,604),part('f2-wall-22','wall',3279,1821,129,1488),part('f2-opening-13','opening',2209,3413,781,198),part('f2-opening-14','opening',3210,3792,198,898),part('f2-opening-11','opening',3469,3309,781,121),part('f2-opening-12','opening',5121,3309,1191,121),part('f2-opening-10','opening',7011,721,99,1190),part('f2-wall-31','wall',7011,1911,99,2800),part('f2-opening-18','opening',10411,1113,198,2748),part('f2-stairs','stair',3408,4690,1834,2252),part('f2-opening-15','opening',6092,4690,807,125),part('f2-opening-16','opening',7020,4897,112,1001),part('f2-wall-34','wall',10411,3861,198,850),part('f2-opening-05','opening',11899,1001,199,3710),part('f2-wall-35','wall',7011,4711,4297,186),part('f2-wall-02','wall',4401,0,6208,203)];
let initial=augmentState(synthetic);
if(process.env.MASTER_SUITE_FIXTURE){const doc=JSON.parse(readFileSync(process.env.MASTER_SUITE_FIXTURE,'utf8'));initial=structuredClone((doc.project||doc).variants[0].state);}
const before=structuredClone(initial),dry=applyMasterSuite(initial,'dry'),window=applyMasterSuite(initial,'window');
assert.deepEqual(initial,before,'must not mutate latest project');assert.deepEqual(dry.floors[0],initial.floors[0],'floor1 must retain all owner edits');
for(const s of [dry,window]){
 assert(validateState(s),'generated state passes full schema');const f=s.floors[1],scene=computeScene(f);assert(scene.valid);
 const facts=inspectMasterSuite(s)!;assert.equal(facts.overlaps.length,0,'default physical suite furniture does not intersect');
 assert(facts.privateAreaM2!>30&&facts.privateAreaM2!<45,'closed suite area is geometrically computed');
 for(const p of f.pieces.filter(p=>p.visible!==false&&p.type==='furniture'&&p.id.startsWith('f2-suite-')&&p.elevationMm===0))for(const sh of pieceShapes(p).filter(v=>v.kind!=='operation'))for(const wall of scene.shapes.filter(v=>v.kind==='wall'))assert(multiArea(intersection([[sh.ring]],[[wall.ring]]))<1,`${p.id} overlaps wall ${wall.objectId}`);
 assert.equal(f.pieces.find(p=>p.id==='f2-opening-13')!.visible,false);
 assert(scene.shapes.some(p=>p.objectId==='f2-suite-old-door-infill'),'old bedroom doorway really closes');
 assert(!pointInMulti([2500,3500],scene.walking),'closed olddoor is not traversable');
 for(const untouched of ['f2-opening-14','f2-wall-06','f2-stairs','f2-opening-15','f2-opening-16'])assert.deepEqual(f.pieces.find(p=>p.id===untouched),before.floors[1].pieces.find(p=>p.id===untouched),'independent westroom/stair/structural stub preserved');
 const water=f.pieces.find(p=>p.id==='f2-suite-public-water')!;const waterBox=bbox(pieceShapes(water)[0].ring);assert(waterBox.x>=5432&&waterBox.x+waterBox.w<=7020&&waterBox.y>=4815&&waterBox.y+waterBox.h<=5898,'water cabinet stays in public central room');assert.equal(f.pieces.find(p=>p.id==='f2-opening-11')!.visible,false);assert(!pointInMulti([3850,3370],scene.walking),'old0.8 hall door is physically closed');
 assert.equal(f.pieces.filter(p=>p.id==='f2-suite-makeup-desk').length,1,'one makeup location per version');if(facts.kind==='window'){const lounger=f.pieces.find(p=>p.id==='f2-suite-lounger')!;assert(lounger&&lounger.w===700&&lounger.h===1900,'fully lying lounger footprint retained');assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-lounger-side-clearance')!.value,540,'actual side cleanup distance remains visible');const mirror=f.pieces.find(p=>p.id==='f2-suite-makeup-mirror')!;const mb=bbox(pieceShapes(mirror)[0].ring);assert(mb.y>=3861&&mb.y+mb.h<=4711&&mb.x>=10609,'mirror remains on window side of fixed lower balcony wall');const table=f.pieces.find(p=>p.id==='f2-suite-makeup-desk')!,tb=bbox(pieceShapes(table)[0].ring);assert.equal(table.rotation,270);assert.equal(tb.x,10629);assert.equal(tb.x+tb.w,11079);assert.equal(tb.y+tb.h,4711);assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-makeup-chair-retreat')!.value,300);assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-makeup-chair-retreat')!.axis,'horizontal');assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-makeup-chair-window')!.value,320,'actual seated rear clearance to window is explicit');assert.equal(lounger.y,1100,'lounger relocated to upper end clear of vanity');assert.equal(f.pieces.find(p=>p.id==='f2-suite-makeup-desk')!.w,900);}else assert(!f.pieces.some(p=>p.id==='f2-suite-lounger'),'dry alternative balcony remains open');
 const bed=f.pieces.find(p=>p.id==='f2-suite-bed')!;assert.equal(bed.w,2100);assert(bed.source!.includes('2000'));assert.equal(bed.x,7710);assert.equal(bed.y,2461);assert.equal(bed.rotation,180);assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-bed-head-wall')!.value,0,'rotated head directly contacts lower wall');assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-bed-foot-open')!.value,2258,'new north-facing foot area measured against original wall');assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-bed-left')!.value,600,'left clearance follows rotated local edge');assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-bed-right')!.value,601,'right clearance follows rotated local edge');const bedVolumes=spatialVolumes(f).filter(v=>v.objectId===bed.id),head=bbox(bedVolumes.find(v=>v.partId==='bed-headboard')!.polygon[0]);assert.equal(Math.round(head.y+head.h),4711,'three-dimensional headboard contacts the same south wall');const pillows=bedVolumes.filter(v=>v.partId.startsWith('bed-pillow'));assert.equal(pillows.length,2);assert(pillows.every(v=>bbox(v.polygon[0]).y>4000),'3D pillows rotate to south head end, not left at old north head');for(const key of ['bedside-left','bedside-right']){const bedside=f.pieces.find(p=>p.id==='f2-suite-'+key)!;assert.equal(bedside.y,4241);assert.equal(bedside.rotation,180);assert.equal(bedside.groupId,bed.groupId);}assert(f.pieces.filter(p=>p.type==='opening'&&p.visible!==false).every(p=>pieceShapes(p).every(a=>pieceShapes(bed).every(b=>multiArea(intersection([[a.ring]],[[b.ring]]))<1))),'bed does not cover any retained door or window aperture');
 assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-wardrobe-aisle')!.value,2403,'recess wardrobe connects original0.8 to private dressing area');
 assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-tub-approach')!.value,1080,'childcare band fits without hitting shower partition');
 assert.equal(facts.dimensions.find(d=>d.id==='f2-suite-wc-front-clearance')!.value,610);
 for(const r of f.routes!.filter(r=>r.id.startsWith('f2-suite-')))for(const a of r.points){const p=anchorPoint(f,a)!;assert(pointInMulti(p,scene.walking),`${r.name} endpoint/waypoint lies in actual free area ${p}`);}
 if(process.env.MASTER_SUITE_FIXTURE){
  const requests=f.routes!.filter(r=>r.id.startsWith('f2-suite-')).map(r=>({...r,points:r.points.map(a=>anchorPoint(f,a)!)}));
  const results=analyzeRoutes({requestId:1,floorId:'f2',free:scene.walking,outline:f.outline as [number,number][],requests,resolution:25}).results;
  assert(results.every(r=>!['invalid','blocked'].includes(r.status)),'all designed relationships are geometrically connected');
  console.log(facts.kind,results.map(r=>({name:r.name,status:r.status,width:Math.round(r.width||0)})));
 }
 const elevated=f.pieces.filter(p=>p.id.startsWith('f2-suite-')&&p.elevationMm!>0);assert.equal(elevated.filter(p=>p.id.endsWith('mirror')).length,2,'vertical mirrors retained');const machine=elevated.find(p=>p.id==='f2-suite-drinking-machine')!;assert(machine&&machine.elevationMm===920&&machine.heightMm===420,'physical drinking machine is visible in the open bay');const machineLocal=pieceShapes(machine)[0].ring.map(p=>toLocal(water,p));assert(machineLocal.every(p=>p[0]>=20&&p[0]<=490-20&&p[1]>=20&&p[1]<=430),'rotated machine fits left open bay');assert(machine.elevationMm!>=918&&machine.elevationMm!+machine.heightMm!<1455,'machine clears shelf spacing');
}
assert.equal(inspectMasterSuite(window)!.wardrobeFacadeMm-inspectMasterSuite(dry)!.wardrobeFacadeMm,1000,'makeup tradeoff is exactly measured facade length');
assert.equal(suiteComparison('dry').referenceAreas.total,39.2);assert.equal(suiteComparison('dry').referenceAreas.private,39.2);assert.equal(suiteComparison('dry').referenceAreas.public,2);assert.equal(inspectMasterSuite(dry)!.dimensions.find(d=>d.id==='f2-suite-stair-hall-clearance')!.value,1260,'hall frontage correctly measures original stairs');const enlarged=structuredClone(dry),stair=enlarged.floors[1].pieces.find(p=>p.id==='f2-stairs')!;stair.y-=600;stair.h+=600;assert.equal(inspectMasterSuite(enlarged)!.dimensions.find(d=>d.id==='f2-suite-stair-hall-clearance')!.value,660,'enlarged stairs update clear hall strip');
const again=applyMasterSuite(dry,'window');assert.equal(again.floors[1].pieces.filter(p=>p.id.startsWith('f2-suite-')).length,window.floors[1].pieces.filter(p=>p.id.startsWith('f2-suite-')).length,'reapply does not duplicate objects');
assert.equal(new Set(again.floors[1].pieces.map(p=>p.id)).size,again.floors[1].pieces.length);
const toggled=structuredClone(dry),f=toggled.floors[1];for(const p of f.pieces.filter(p=>p.id==='f2-suite-wardrobe-west'||p.id==='f2-suite-wardrobe-east'))p.usage!.open=true;
const openScene=computeScene(f);assert(multiArea(openScene.walking)<multiArea(computeScene(dry.floors[1]).walking),'cabinet opening actually subtracts floor use area');
const withdrawal=structuredClone(dry),chair=withdrawal.floors[1].pieces.find(p=>p.id==='f2-suite-makeup-chair')!;chair.usage!.open=true;assert(multiArea(computeScene(withdrawal.floors[1]).walking)<multiArea(computeScene(dry.floors[1]).walking),'seat withdrawal changes walking area');
for(const state of [dry,window]){const moved=structuredClone(state.floors[1]),desk=moved.pieces.find(p=>p.id==='f2-suite-makeup-desk')!,initialGroup=structuredClone(moved.pieces.filter(p=>p.groupId===desk.groupId));assert.equal(initialGroup.length,4);patchGroupedPiece(moved,desk.id,{x:desk.x+100,y:desk.y+75},true);for(const old of initialGroup){const p=moved.pieces.find(p=>p.id===old.id)!;assert.equal(p.x-old.x,100);assert.equal(p.y-old.y,75);}assert.equal(moved.pieces.find(p=>p.id==='f2-suite-double-vanity')!.groupId,moved.pieces.find(p=>p.id==='f2-suite-vanity-mirror')!.groupId);assert.equal(moved.pieces.find(p=>p.id==='f2-suite-tub')!.groupId,moved.pieces.find(p=>p.id==='f2-suite-tub-care')!.groupId);const bed=moved.pieces.find(p=>p.id==='f2-suite-bed')!,bedGroup=structuredClone(moved.pieces.filter(p=>p.groupId===bed.groupId));assert.equal(bedGroup.length,3);patchGroupedPiece(moved,bed.id,{x:bed.x+75,y:bed.y-90},true);for(const old of bedGroup){const p=moved.pieces.find(p=>p.id===old.id)!;assert.equal(p.x-old.x,75);assert.equal(p.y-old.y,-90);}}
const oldMirrors=dry.floors[1].pieces.filter(p=>p.id.endsWith('mirror'));assert(oldMirrors.every(p=>p.elevationMm!>1000),'mirrors have actual installation elevations');
console.log('PASS independent suites, real closure, public service access, exact measurements, use states and source preservation');
