import assert from 'node:assert/strict';
import {elevationItems,elevationSvgContent,pieceElevation,pieceHeight,sectionIntervals,spatialBriefSvg,spatialVolumes,spatialWarnings} from '../lib/brief-export';
import {pointInRing,ringArea} from '../lib/geometry';
import {rectRing} from '../lib/measurement-model';
import type {Floor,Piece} from '../lib/model';

const base:Floor={id:'test',name:'空间测试',outline:rectRing(0,0,6000,5000),originalOutline:rectRing(0,0,6000,5000),pieces:[],rooms:[],source:'fixture',note:'',ceilingHeightMm:3000,heightSource:'provisional'};
const wall:Piece={id:'wall',name:'墙',type:'wall',x:0,y:0,w:5000,h:200,rotation:0,heightMm:3000,elevationMm:0,dimensionSource:'measured'};
const window:Piece={id:'window',name:'窗',type:'opening',openingKind:'window',x:1500,y:0,w:1500,h:200,rotation:0,heightMm:1200,elevationMm:900,dimensionSource:'measured',hostWallIds:['wall']};
const floor={...base,pieces:[wall,window]},volumes=spatialVolumes(floor);
const at=(x:number,y:number,z:number)=>volumes.filter(v=>v.kind==='wall'&&v.bottom<z&&v.top>z&&pointInRing([x,y],v.polygon[0]));
assert.equal(at(2000,100,1500).length,0,'window opens only its actual aperture');
assert.equal(at(2000,100,400).length,1,'sill retains wall below window');
assert.equal(at(2000,100,2500).length,1,'lintel retains wall above window');
assert.equal(at(500,100,1500).length,1,'adjacent solid wall stays');
const door={...window,id:'door',openingKind:'door' as const,elevationMm:0,heightMm:2100},doorVolumes=spatialVolumes({...base,pieces:[structuredClone(wall),door]});
assert(!doorVolumes.some(v=>v.kind==='wall'&&v.bottom<1000&&v.top>1000&&pointInRing([2000,100],v.polygon[0])));
assert(doorVolumes.some(v=>v.kind==='wall'&&v.bottom<2500&&v.top>2500&&pointInRing([2000,100],v.polygon[0])));
const l:Piece={id:'l',name:'L 台面',type:'furniture',x:300,y:400,w:3000,h:2000,rotation:0,baseW:3000,baseH:2000,heightMm:850,parts:[{id:'body',name:'L 占地',ring:[[0,0],[3000,0],[3000,600],[600,600],[600,2000],[0,2000]]}]};
const lv=spatialVolumes({...base,pieces:[l]})[0];assert.equal(Math.round(ringArea(lv.polygon[0])),2640000);
assert.deepEqual(sectionIntervals(lv.polygon,'north',1500),[[300,900]],'section keeps L void empty');
assert.deepEqual(sectionIntervals(lv.polygon,'north',700),[[300,3300]]);
const rotated={...l,rotation:90};const rv=spatialVolumes({...base,pieces:[rotated]})[0];assert.equal(Math.round(ringArea(rv.polygon[0])),2640000);assert.notDeepEqual(rv.polygon,lv.polygon);
const holed=[rectRing(0,0,4000,2000),rectRing(1000,500,2000,1000)];assert.deepEqual(sectionIntervals(holed,'north',1000),[[0,1000],[3000,4000]],'section respects polygon holes');
const cabinet:Piece={id:'cabinet',name:'书柜',type:'furniture',x:1000,y:1000,w:1200,h:400,rotation:0,heightMm:2400,dimensionSource:'design',cabinet:{columns:[{width:600,shelves:3,drawers:1,open:false,hinge:'left'},{width:600,shelves:2,drawers:0,open:true,hinge:'none'}],plinthMm:80,topGapMm:20,doorOpen:false}};
const closed=spatialVolumes({...base,pieces:[cabinet]}),opened=spatialVolumes({...base,pieces:[{...cabinet,cabinet:{...cabinet.cabinet!,doorOpen:true}}]});
assert(closed.some(v=>v.partId==='cab-shelf-0-3'));assert(closed.some(v=>v.partId==='cab-drawer-0-1'));assert(!closed.some(v=>v.partId==='cab-door-1'));
assert(opened.some(v=>v.partId==='cab-door-open-0'&&Math.max(...v.polygon[0].map(p=>p[1]))>cabinet.y+cabinet.h));
assert.equal(Math.max(...closed.map(v=>v.top)),2380,'top gap retained');
const island:Piece={id:'i',name:'餐岛',type:'furniture',x:0,y:0,w:2000,h:800,rotation:0,heightMm:900,parts:[{id:'body',name:'台面',ring:rectRing(0,0,2000,800)},{id:'chair-n1',name:'椅',ring:rectRing(0,-500,500,500)}],partHeightsMm:{body:850,'chair-n1':780}};
const iv=spatialVolumes({...base,pieces:[island]});assert.equal(Math.max(...iv.filter(v=>v.partId.startsWith('body')).map(v=>v.top)),850);assert.equal(Math.max(...iv.filter(v=>v.partId.startsWith('chair')).map(v=>v.top)),780);
assert.equal(pieceHeight(window),1200);assert.equal(pieceElevation(window),900);
assert(spatialWarnings({...base,pieces:[{...cabinet,heightMm:4000}]}).some(s=>s.includes('高于当前层高')));
const elevation=elevationSvgContent({floor:{...base,pieces:[cabinet]},selected:'cabinet',focus:true});assert(elevation.body.includes('高 2400'));assert(elevation.body.includes('书柜'));assert(elevation.viewBox.every(Number.isFinite));
const cut=elevationItems({...base,pieces:[l]},'north',1500);assert.equal(cut[0].right-cut[0].left,600);
const exported=spatialBriefSvg({floor:{...base,pieces:[cabinet]},selected:'cabinet',variantName:'方案 B',revision:7});assert(exported.includes('方案 B'));assert(exported.includes('2400'));assert(exported.includes('Microsoft YaHei'));assert(exported.includes('未签发施工'));
const escaped=spatialBriefSvg({floor:{...base,name:'<img onerror="bad">',pieces:[]}});assert(!escaped.includes('<img'));assert(escaped.includes('&lt;img'));
const roomExport=spatialBriefSvg({floor:{...base,pieces:[cabinet,l],rooms:[{id:'r',name:'设计讨论区域',x:0,y:0,w:800,h:900}]},roomName:'设计讨论区域',selected:'cabinet'});assert(roomExport.includes('交底圈选范围'));assert(roomExport.includes('不代表已实测的闭合房间'));assert(!roomExport.includes('书柜：宽'));assert(roomExport.includes('L 台面'));assert.throws(()=>spatialBriefSvg({floor:base,roomName:'不存在'}),/没有该空间/);
const beam:Piece={id:'beam',name:'梁',type:'furniture',architecturalKind:'beam',x:0,y:0,w:4000,h:250,heightMm:350,elevationMm:2600,rotation:0};const bv=spatialVolumes({...base,pieces:[beam]})[0];assert.equal(bv.kind,'overhead');assert.equal(bv.bottom,2600);assert.equal(bv.top,2950);
console.log('PASS spatial opening elevations, L/rotated/hole sections, cabinet operation, part heights and brief export');
