import React,{useState} from 'react';
import Studio from '../app/Studio';
import {createRoot} from 'react-dom/client';
import {listLocalReferences} from '../lib/local-references';
import {validateState,type State} from '../lib/model';
import {downloadJson} from '../lib/project-client';
import '../app/globals.css';
import '../app/studio.css';
function Migration(){const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[legacy,setLegacy]=useState<{Editor:any;state:State}|null>(null);async function exportLocal(){setBusy(true);try{const raw=localStorage.getItem('xian-home-guest');if(!raw)throw Error('当前浏览器未发现旧版草稿。请在原来编辑过的浏览器打开此页。');const state=JSON.parse(raw);if(!validateState(state))throw Error('本机草稿格式异常；请保留浏览器数据并联系我检查。');const references=[];for(const ref of await listLocalReferences()){const blob=await(await fetch(ref.url)).blob(),image=await new Promise<string>((yes,no)=>{const reader=new FileReader();reader.onload=()=>yes(String(reader.result));reader.onerror=no;reader.readAsDataURL(blob);});references.push({...ref,url:undefined,image});}downloadJson({format:'xian-home-legacy-complete',version:1,state,references,exportedAt:new Date().toISOString()},'西安的家-旧版布局及图片.json');setStatus(`已导出两层布局和 ${references.length} 张参考图片。旧浏览器数据保留。`);}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}async function openLegacy(){setBusy(true);try{const [{default:Editor},{default:seed}]=await Promise.all([import('../app/Editor'),import('../data/seed.json')]);setLegacy({Editor,state:seed as State});}finally{setBusy(false);}}
 if(legacy)return <><div className="studio-notice"><a href="https://jmryqyx.cn/xian-home/">打开新版工作台</a><button onClick={()=>setLegacy(null)}>返回迁移与完整导出</button><span>这是旧版本机副本，不会自动同步到新版。</span></div><legacy.Editor initial={legacy.state} guest offline/></>;
 return <main className="studio-login"><section className="login-story"><span className="studio-kicker">西安的家 / 工作台已升级</span><h1>两层布局，<br/>在同一处继续。</h1><p>实时尺寸 · 立面三维 · 设计师查看</p><svg viewBox="0 0 520 300" aria-hidden="true"><path d="M30 30H330V70H480V270H220V215H95V165H30ZM220 215V140H330V270M95 165H160V30M330 140H480" fill="none" stroke="currentColor" strokeWidth="2"/></svg></section><section className="login-card"><span className="studio-kicker">正式入口与旧版迁移</span><h2>打开空间研究室</h2><p>家人可直接查看新版布局与效果图。您的本机旧布局及参考图片不会因升级而被删除。</p><a href="https://jmryqyx.cn/xian-home/" className="primary" style={{display:'block',textAlign:'center',padding:12,textDecoration:'none',borderRadius:6}}>进入新版工作台 →</a><h3 style={{fontSize:15,marginTop:30}}>带上旧浏览器里的调整</h3><p>先导出旧版布局及图片，再到新版“分享与备份”导入，会另存为独立方案。</p><button onClick={exportLocal} disabled={busy}>导出旧版布局及全部图片</button><button onClick={openLegacy} disabled={busy} style={{marginTop:10}}>继续查看旧版本机副本</button>{status&&<p role="status">{status}</p>}<p className="fine-note">GitHub 入口展示本次发布的家庭查看版本；本机旧布局仍可单独导出。</p></section></main>;
}
class Boundary extends React.Component<{children:React.ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<main className="login-card"><h1>页面需要重新加载</h1><p>本机草稿仍保留，请刷新重试。</p><button onClick={()=>location.reload()}>重新加载</button></main>:this.props.children;}}
const legacy=new URLSearchParams(location.search).get('legacy')==='1';
createRoot(document.getElementById('root')!).render(<Boundary>{legacy?<Migration/>:<Studio/>}</Boundary>);
