'use client';
import {useState} from 'react';
import type {Piece} from '../lib/model';
import {riskText} from '../lib/model';
import {dimensionSourceLabels,pieceElevation,pieceHeight} from '../lib/brief-export';
import './spatial.css';

export type CabinetEditorProps={piece:Piece;onChange:(patch:Partial<Piece>)=>void;readOnly?:boolean};
const finite=(n:number,min:number,max:number)=>Number.isFinite(n)&&n>=min&&n<=max;
export function initialCabinet(width:number){const n=Math.max(1,Math.min(8,Math.ceil(width/650)));return {columns:Array.from({length:n},(_,i)=>({width:i===n-1?width-Math.floor(width/n)*(n-1):Math.floor(width/n),shelves:3,drawers:0,open:false,hinge:'left' as const})),plinthMm:80,topGapMm:20,doorOpen:false};}

export default function CabinetEditor({piece,onChange,readOnly=false}:CabinetEditorProps){
 const [error,setError]=useState(''),cabinet=piece.cabinet;
 function patch(value:Partial<Piece>){if(readOnly)return;setError('');onChange(value);}
 function numeric(field:'heightMm'|'elevationMm',value:string){const n=Number(value);if(!value.trim()||!finite(n,field==='heightMm'?10:0,12000)){setError('请输入有效毫米尺寸，高度 10—12000，离地 0—12000。');return;}if(field==='heightMm'&&cabinet&&n<=cabinet.plinthMm+cabinet.topGapMm+40){setError('柜高需大于踢脚、顶部留空，并保留至少 40 mm 柜内空间。');return;}if(Math.round(n)===(field==='heightMm'?pieceHeight(piece):pieceElevation(piece)))return;patch({[field]:Math.round(n),dimensionSource:piece.dimensionSource==='measured'||piece.dimensionSource==='drawing'?'design':piece.dimensionSource||'design'});}
 function updateCabinet(change:Partial<NonNullable<Piece['cabinet']>>){if(cabinet)patch({cabinet:{...cabinet,...change}});}
 function setColumn(i:number,change:Partial<NonNullable<Piece['cabinet']>['columns'][number]>){if(!cabinet)return;const columns=cabinet.columns.map(c=>({...c}));if(change.width!==undefined){if(!finite(change.width,100,10000)){setError('单列宽度需在 100—10000 mm 之间。');return;}const delta=change.width-columns[i].width,j=i===columns.length-1?i-1:i+1;if(j<0&&Math.abs(change.width-piece.w)>.5){setError('只有一列时，列宽应与柜体总宽一致；请先修改柜体宽度。');return;}if(j>=0){if(columns[j].width-delta<100){setError('相邻列至少保留 100 mm，请先调整总宽或分列数量。');return;}columns[j].width-=delta;}}if(change.shelves!==undefined&&!finite(change.shelves,0,20)||change.drawers!==undefined&&!finite(change.drawers,0,12)){setError('层板数量 0—20，抽屉数量 0—12。');return;}Object.assign(columns[i],change);updateCabinet({columns});}
 return <section className="cabinet-editor" aria-label="高度与柜体参数"><h3>高度与立面</h3><div className="spatial-field-grid"><label>实体高度 mm<input type="number" min="10" max="12000" key={piece.id+':h:'+piece.heightMm} defaultValue={pieceHeight(piece)} disabled={readOnly} onBlur={e=>numeric('heightMm',e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label><label>底部离完成地面 mm<input type="number" min="0" max="12000" key={piece.id+':z:'+piece.elevationMm} defaultValue={pieceElevation(piece)} disabled={readOnly} onBlur={e=>numeric('elevationMm',e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label></div><label className="spatial-full-field">尺寸来源<select value={piece.dimensionSource||'provisional'} disabled={readOnly} onChange={e=>patch({dimensionSource:e.target.value as Piece['dimensionSource']})}>{Object.entries(dimensionSourceLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><p className="spatial-help">平面“深”与立面“高”分别保存。顶标高 +{pieceElevation(piece)+pieceHeight(piece)} mm。</p>
  {(piece.type==='stair'||piece.type==='wall'&&piece.structural!=='nonload')&&<p className="spatial-error-inline" role="note">{riskText(piece)}</p>}
  {piece.architecturalKind&&<p className="spatial-help">{piece.architecturalKind==='beam'?'梁':'吊顶'}底标高 +{pieceElevation(piece)} mm；竖向尺寸需与现场复尺一致，方案调整不代表原构件可拆。</p>}
  {piece.type==='furniture'&&!piece.architecturalKind&&!cabinet&&<button className="spatial-primary" disabled={readOnly} onClick={()=>patch({cabinet:initialCabinet(piece.w),heightMm:piece.heightMm||2400,dimensionSource:'design'})}>设为可编辑柜体</button>}
  {cabinet&&<><div className="cabinet-title"><h3>柜体分格</h3><button disabled={readOnly} onClick={()=>patch({cabinet:undefined})}>恢复普通家具</button></div><div className="spatial-field-grid"><label>踢脚高度 mm<input type="number" min="0" max="500" value={cabinet.plinthMm} disabled={readOnly} onChange={e=>{const n=Number(e.target.value);if(finite(n,0,500)&&n+cabinet.topGapMm<pieceHeight(piece)-40)updateCabinet({plinthMm:n});else setError('踢脚与顶部留空应小于柜高，并保留柜内空间。');}}/></label><label>顶部留空 mm<input type="number" min="0" max="1500" value={cabinet.topGapMm} disabled={readOnly} onChange={e=>{const n=Number(e.target.value);if(finite(n,0,1500)&&n+cabinet.plinthMm<pieceHeight(piece)-40)updateCabinet({topGapMm:n});else setError('顶部留空应小于柜高，并保留柜内空间。');}}/></label></div><div className="cabinet-state"><label><input type="checkbox" checked={cabinet.doorOpen} disabled={readOnly} onChange={e=>updateCabinet({doorOpen:e.target.checked})}/> 柜门开启 90°</label><span>分格合计 {Math.round(cabinet.columns.reduce((s,c)=>s+c.width,0))} / 总宽 {Math.round(piece.w)}</span></div>
  {cabinet.columns.map((col,i)=><fieldset key={piece.id+':'+i} disabled={readOnly} className="cabinet-column"><legend>第 {i+1} 列</legend><div className="spatial-field-grid"><label>列宽 mm<input type="number" min="100" key={piece.id+':'+i+':'+col.width} defaultValue={col.width} onBlur={e=>{if(e.target.value.trim())setColumn(i,{width:Math.round(Number(e.target.value))});}}/></label><label>门形式<select value={col.open?'open':col.hinge} onChange={e=>setColumn(i,e.target.value==='open'?{open:true,hinge:'none'}:{open:false,hinge:e.target.value as 'left'|'right'|'none'})}><option value="left">左铰门</option><option value="right">右铰门</option><option value="none">无门板</option><option value="open">开放格</option></select></label><label>层板数量<input type="number" min="0" max="20" value={col.shelves} onChange={e=>setColumn(i,{shelves:Math.round(Number(e.target.value))})}/></label><label>抽屉数量<input type="number" min="0" max="12" value={col.drawers} onChange={e=>setColumn(i,{drawers:Math.round(Number(e.target.value))})}/></label></div></fieldset>)}
  <div className="spatial-button-row"><button disabled={readOnly||cabinet.columns.length>=12||piece.w/(cabinet.columns.length+1)<100} onClick={()=>{const n=cabinet.columns.length+1,w=Math.floor(piece.w/n);updateCabinet({columns:Array.from({length:n},(_,i)=>({...cabinet.columns[Math.min(i,cabinet.columns.length-1)],width:i===n-1?piece.w-w*(n-1):w}))});}}>增加一列并均分</button><button disabled={readOnly||cabinet.columns.length<=1} onClick={()=>{const n=cabinet.columns.length-1,w=Math.floor(piece.w/n);updateCabinet({columns:cabinet.columns.slice(0,n).map((c,i)=>({...c,width:i===n-1?piece.w-w*(n-1):w}))});}}>减少一列并均分</button></div><p className="spatial-help">分格为设计意向；板厚、五金、门板受力及实际加工尺寸由定制厂家深化。柜门前方范围随开启状态显示。</p></>}
  {error&&<p role="alert" className="spatial-error-inline">{error}</p>}
 </section>;
}
export {CabinetEditor};
