'use client';
import type {Floor,Piece} from '../lib/model';
import type {Dimension,Scene} from '../lib/geometry';
import type {RouteResult} from '../lib/routes';
import {dimensionText} from './MeasurementLayer';
export type BuildMode='none'|'point'|'object'|'edge'|'route'|'region';
export default function MeasurementPanel({floor,piece,scene,dimensions,routes,routeStatus,focus,mode,draftCount,onMode,onFinish,onPick,onPin,onRename,onRemove,onMeasureMode,onRouteTarget,onUsage,onOpening,onExport,exporting,onRemoveRegion}:{floor:Floor;piece?:Piece;scene:Scene;dimensions:Dimension[];routes:RouteResult[];routeStatus:string;focus:string;mode:BuildMode;draftCount:number;onMode:(m:BuildMode)=>void;onFinish:()=>void;onPick:(d:Dimension)=>void;onPin:(d:Dimension)=>void;onRename:(id:string,name:string)=>void;onRemove:(id:string)=>void;onMeasureMode:(id:string,mode:string)=>void;onRouteTarget:(r:RouteResult,value:number)=>void;onUsage:(patch:NonNullable<Piece['usage']>)=>void;onOpening:(patch:Partial<Piece>)=>void;onExport:(kind:'pdf'|'svg'|'dxf'|'csv')=>void;exporting:boolean;onRemoveRegion:(id:string)=>void}){
 const chosen=dimensions.find(d=>d.id===focus);return <>
 <section className="property-section measurement-panel"><div className="section-heading"><h3>实时尺寸</h3><span className="tag">{dimensions.length} 项</span></div>
 <div className="measurement-tools">{([['point','两点'],['object','两对象'],['edge','两条边'],['route','画路线'],['region','圈区域']] as [BuildMode,string][]).map(([m,label])=><button key={m} className={mode===m?'active':''} onClick={()=>onMode(mode===m?'none':m)}>{label}</button>)}</div>
 {mode!=='none'&&<div className="drawing-instruction"><p>{mode==='route'?'依次点选起点、途经点、终点。':mode==='region'?'依次点选区域顶点，再闭合区域。':`在图上依次选择${mode==='object'?'两个对象':mode==='edge'?'两条边':'两个测量点'}。`}</p>{['route','region'].includes(mode)&&<button onClick={onFinish} disabled={draftCount<(mode==='region'?3:2)}>{mode==='region'?'闭合区域':'完成路线'} · {draftCount} 点</button>}<button onClick={()=>onMode('none')}>取消</button></div>}
 {chosen&&<div className="selected-dimension"><strong>{dimensionText(chosen)}</strong><input key={chosen.id+chosen.name} aria-label="尺寸名称" defaultValue={chosen.name} onBlur={e=>onRename(chosen.id,e.target.value)}/><p>{chosen.note}</p><div className="dimension-actions"><button onClick={()=>onPin(chosen)}>{chosen.spec?.pinned?'取消固定':'固定显示'}</button>{chosen.spec&&floor.measurements?.some(m=>m.id===chosen.id)&&<button onClick={()=>onRemove(chosen.id)}>删除关系</button>}</div>{chosen.spec&&floor.measurements?.some(m=>m.id===chosen.id)&&<label className="select-label">测量方式<select value={chosen.spec.mode} onChange={e=>onMeasureMode(chosen.id,e.target.value)}><option value="shortest">实体最短净距</option><option value="horizontal">水平投影净距</option><option value="vertical">垂直投影净距</option><option value="direct">锚点直线距离</option></select></label>}<small>{floor.measurements?.some(m=>m.id===chosen.id)?'橙色端点可拖动，更改测量位置。':'固定尺寸后可拖动端点，调整测量位置。'}</small></div>}
 <details className="dimension-list" open><summary>尺寸清单 · 点击定位</summary>{dimensions.map((d,i)=><button key={d.id} className={focus===d.id?'active':''} onClick={()=>onPick(d)}><span className="dimension-index">{i+1}</span><span>{d.name}<small>{d.category==='size'?'外尺寸':d.estimated?'估算':'几何计算'}{d.spec?.pinned?' · 已固定':''}</small></span><b className={d.status==='overlap'?'warn':''}>{dimensionText(d)}</b></button>)}</details>
 </section>
 {piece?.type==='opening'&&<section className="property-section"><h3>门窗与墙体关联</h3><label className="select-label">类型<select value={piece.openingKind||'window'} onChange={e=>onOpening({openingKind:e.target.value as Piece['openingKind']})}><option value="door">门洞，可通行</option><option value="opening">开放洞口，可通行</option><option value="window">窗户，不通行</option></select></label><label className="select-label">关联墙段（可多选）<select multiple size={4} value={piece.hostWallIds||[]} onChange={e=>onOpening({hostWallIds:Array.from(e.target.selectedOptions).map(o=>o.value)})}>{floor.pieces.filter(p=>p.type==='wall').map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><p className="fine-note">新门洞只切开关联墙段。原墙调整仍需结构复核。</p></section>}
 {piece?.type==='furniture'&&<section className="property-section usage-panel"><h3>家具使用状态</h3>{piece.id==='f1-island'&&<><label className="select-label">餐桌<select value={piece.usage?.table||'compact'} onChange={e=>onUsage({table:e.target.value as any})}><option value="compact">常态4人</option><option value="extended">展开6人</option></select></label><label className="select-label">餐椅<select value={piece.usage?.chairs||'seated'} onChange={e=>onUsage({chairs:e.target.value as any})}><option value="seated">就座／拉出</option><option value="stored">收起</option></select></label></>}
 <label className="check-label"><input type="checkbox" checked={!!piece.usage?.open} onChange={e=>onUsage({open:e.target.checked})}/>显示柜门／椅后使用范围</label><div className="usage-inputs"><label>向外预留 mm<input aria-label="使用预留深度" type="number" min="0" max="3000" value={piece.usage?.depth??''} placeholder="待补充" onChange={e=>onUsage({depth:Math.max(0,Math.min(3000,Number(e.target.value)))})}/></label><label>方向<select value={piece.usage?.side||'bottom'} onChange={e=>onUsage({side:e.target.value as any})}><option value="bottom">下侧</option><option value="top">上侧</option><option value="left">左侧</option><option value="right">右侧</option></select></label></div><small>{piece.usage?.depth?'使用范围参与通道计算；可按实际产品修改。':'使用范围待补充；尚未计入柜门开启及椅后操作空间。'}</small></section>}
 <section className="property-section"><h3>区域面积</h3>{!scene.valid?<p className="error-text">{scene.error}</p>:<><dl className="area-summary"><dt>外轮廓含墙面积</dt><dd>{scene.outerArea.toFixed(2)} ㎡</dd><dt>扣墙地面面积</dt><dd>{scene.netArea.toFixed(2)} ㎡</dd><dt>剩余空地</dt><dd>{scene.emptyArea.toFixed(2)} ㎡</dd></dl><details className="area-list"><summary>各空间 · {scene.rooms.length}</summary>{scene.rooms.map(r=><div key={r.id}><b>{r.name}</b><span>{r.polygon.length?`${r.area.toFixed(2)} ㎡ · 空地 ${r.freeArea.toFixed(2)} ㎡`:r.status}</span>{r.polygon.length>0&&<small>范围 {Math.round(r.width)} × {Math.round(r.depth)} mm · {r.status}</small>}{r.sourceArea&&<small>原图参考 {r.sourceArea} ㎡</small>}{floor.regions?.some(q=>q.id===r.id)&&<button className="text-button" onClick={()=>onRemoveRegion(r.id)}>删除圈定区域</button>}</div>)}</details></>}</section>
 <section className="property-section"><h3>通道与路线</h3><p className="fine-note route-status" role="status">{routeStatus||'打开画布上方“通道分析”后计算。'}</p>{routes.map((r,i)=><div className="route-result" key={r.id}><b>B{i+1} · {r.name}</b><span className={r.status==='ok'?'':'warn'}>{r.width===null?r.status==='blocked'?'不连通':'端点待调整':`≈ ${Math.round(r.width)} mm${r.status==='borderline'?' · 临界':''}`}</span><label>目标 mm<input type="number" min="100" max="4000" defaultValue={r.target} key={r.id+':'+r.target} onBlur={e=>{const n=Number(e.target.value);if(n>=100&&n<=4000&&n!==r.target)onRouteTarget(r,n);}}/></label><small>{r.note}</small></div>)}</section>
 <section className="property-section"><h3>设计师交接</h3><div className="export-grid">{(['dxf','pdf','svg','csv'] as const).map(k=><button key={k} disabled={exporting} onClick={()=>onExport(k)}>{exporting?'处理中':k.toUpperCase()}</button>)}</div><p className="fine-note">当前楼层与当前显示的标注。全屋交接前打开“全屋尺寸”；保留毫米坐标、测量口径及方案版本。</p></section>
 </>;
}
