import {Floor,Piece,transform,changedPiece} from '../lib/model';
import React from 'react';
import {bbox,pieceShapes,type Scene} from '../lib/geometry';
import {activeParts} from '../lib/measurement-model';
import {getStairPlanSvg} from '../lib/stairs';
export function PieceDrawing({p,selected=false,labels=true,ghost=false,floorId}:{p:Piece;selected?:boolean;labels?:boolean;ghost?:boolean;floorId?:string}){
 const wall=p.type==='wall',struct=wall&&p.structural!=='nonload',fill=wall?(p.structural==='candidate'||p.structural==='confirmed'?'#334a50':'#959f9a'):p.type==='stair'?'#e9edf0':p.type==='opening'?'#dce9ed':p.type==='zone'?'#e6eddf':p.color||'#d9c3a5';
 const bw=p.type==='stair'?p.w:p.baseW||p.w,bh=p.type==='stair'?p.h:p.baseH||p.h;let body;
 const textWidth=Math.max(260,Math.abs(Math.cos(p.rotation*Math.PI/180))*bw+Math.abs(Math.sin(p.rotation*Math.PI/180))*bh-80),perLine=Math.max(3,Math.floor(textWidth/128)),shortName=p.name.split(' · ')[0],nameChars=Array.from(shortName),lines=nameChars.length<=perLine?[shortName]:[nameChars.slice(0,perLine).join(''),nameChars.slice(perLine,perLine*2-1).join('')+(nameChars.length>perLine*2-1?'…':'')];
 const dark=p.color&&/^#[0-9a-f]{6}$/i.test(p.color)&&[1,3,5].map(i=>parseInt(p.color!.slice(i,i+2),16)).reduce((a,b)=>a+b,0)<330,labelColor=dark?'#f8f0e5':'#34494a';
 if(p.type==='stair')body=<g dangerouslySetInnerHTML={{__html:getStairPlanSvg(p,floorId)}}/>;
 else if(p.id==='f1-island'&&p.parts)body=<>{activeParts(p).map(part=><polygon key={part.id} points={part.ring.map(q=>q.join(',')).join(' ')} fill={part.id.includes('chair')||part.id.includes('extra')||part.id.includes('stored')?'#d7d3c8':part.id==='extension'?'#ccac79':'#ddd7c2'} stroke="#72827d" strokeWidth="12"/>)}<rect x="60" y="70" width="450" height="360" rx="40" fill="#edf2ec" stroke="#71837c" strokeWidth="15"/></>;
 else if(p.parts&&p.usage?.chairs&&/椅/.test(p.name))body=<>{activeParts(p).map(part=><g key={part.id}><polygon points={part.ring.map(q=>q.join(',')).join(' ')} fill="#d2c4b2" stroke="#827565" strokeWidth="15"/><path d={`M${part.ring[0].join(' ')}L${part.ring[1].join(' ')}`} fill="none" stroke="#968571" strokeWidth="65" strokeLinecap="round"/></g>)}</>;
 else if(p.architecturalKind)body=<><rect width={bw} height={bh} fill="#d1c9bb55" stroke="#9e856a" strokeWidth="15" strokeDasharray="60 35"/><path d={`M0 0L${bw} ${bh}M${bw} 0L0 ${bh}`} stroke="#ad9980" strokeWidth="7"/></>;
 else if(p.svg)body=<g dangerouslySetInnerHTML={{__html:p.svg}}/>;
 else if(p.type==='opening'&&(p.openingKind==='door'||p.openingKind==='opening'||p.name.includes('门')))body=<><rect width={bw} height={bh} fill="#fffef9"/><path d={bw>bh?`M0 ${bh/2}H${bw}`:`M${bw/2} 0V${bh}`} stroke="#b8a88c" strokeWidth="9" strokeDasharray="50 40"/></>;
 else if(p.type==='opening')body=<><rect width={bw} height={bh} fill={fill} stroke="#7695a1" strokeWidth="14"/><path d={bw>bh?`M0 ${bh/3}H${bw}M0 ${bh*2/3}H${bw}`:`M${bw/3} 0V${bh}M${bw*2/3} 0V${bh}`} stroke="#86a1a9" strokeWidth="9"/></>;
 else body=<><rect width={bw} height={bh} rx={wall?0:50} fill={fill} stroke={wall?'#566964':'#8c998f'} strokeWidth={wall?'5':'12'}/>{p.name.includes('床')&&!/柜|桌|床头灯/.test(p.name)&&<><rect x={bw*.06} y={bh*.08} width={bw*.88} height={bh*.78} rx="35" fill="#f5f3ec" stroke="#b1b4a9" strokeWidth="8"/><rect x={bw*.10} y={bh*.1} width={bw*.34} height={bh*.16} rx="32" fill="#ddd8ce"/><rect x={bw*.55} y={bh*.1} width={bw*.34} height={bh*.16} rx="32" fill="#ddd8ce"/></>}{p.name.includes('柜')&&<path d={`M${bw/2} 0V${bh}`} stroke="#ad9270" strokeWidth="8"/>}{p.name.includes('沙发')&&<rect x="65" y="100" width={Math.max(50,bw-130)} height={Math.max(50,bh-160)} fill="#ede6d9" rx="55" stroke="#ac9f8d" strokeWidth="12"/>}</>;
 return <g transform={transform(p.type==='stair'?{...p,baseW:p.w,baseH:p.h}:p)} opacity={ghost?.27:1} className={ghost?'ghost-object':undefined}>
 <title>{p.name} · {Math.round(p.w)} × {Math.round(p.h)} mm{p.elevationMm?` · 离地 ${p.elevationMm} mm`:''}</title>
 {ghost?<rect width={bw} height={bh} fill="none" stroke="#9e5f48" strokeDasharray="65 38" strokeWidth="16"/>:body}
 {!ghost&&labels&&p.type!=='wall'&&p.type!=='opening'&&p.type!=='stair'&&(!(p.elevationMm&&p.elevationMm>0)||selected)&&<g style={{pointerEvents:'none'}} transform={`rotate(${-p.rotation} ${bw/2} ${bh/2})`}>{lines.map((line,i)=><text key={i} x={bw/2} y={bh/2-32-(lines.length-1)*70+i*140} textAnchor="middle" dominantBaseline="middle" className="plan-label" style={{fill:labelColor}}>{line}</text>)}<text x={bw/2} y={bh/2+130+(lines.length-1)*70} textAnchor="middle" className="plan-size" style={{fill:dark?'#ded2c3':undefined,fontSize:Math.min(107,textWidth/8)}}>{Math.round(p.w+(p.usage?.table==='extended'?600*p.w/(p.baseW||p.w):0))} × {Math.round(p.h)}</text></g>}
 {selected&&!ghost&&<rect x="-32" y="-32" width={bw+64} height={bh+64} fill="none" stroke="#247da0" strokeWidth="16" strokeDasharray="60 35"/>}
 {struct&&changedPiece(p)&&!ghost&&<rect width={bw} height={bh} fill="none" stroke="#bb6d34" strokeWidth="27"/>}
 </g>;
}
export default function Plan({floor,selected,view,grid,original,labels=true,boundary=false,onDown,onBackground,onVertex,onResize,svgRef,measure,previewWall,overlay,scene}:{floor:Floor;selected:string;view:number[];grid:boolean;original:boolean;labels?:boolean;boundary?:boolean;onDown?:(e:React.PointerEvent,p:Piece)=>void;onBackground?:(e:React.PointerEvent)=>void;onVertex?:(e:React.PointerEvent,i:number)=>void;onResize?:(e:React.PointerEvent,p:Piece)=>void;svgRef?:React.RefObject<SVGSVGElement|null>;measure?:number[][];previewWall?:Piece|null;overlay?:React.ReactNode;scene?:Scene}){
 const occupied=floor.pieces.filter(p=>p.visible!==false&&['furniture','stair','zone'].includes(p.type)&&!(p.elevationMm&&p.elevationMm>0)).map(p=>p.type==='zone'?p:pieceShapes(p).filter(s=>s.kind!=='operation').map(s=>bbox(s.ring))).flat();
 const roomLabel=(r:Floor['rooms'][number])=>{const width=r.name.length*148+100,height=210;if(width>r.w-80||height>r.h-80)return null;for(const [u,v]of [[.5,.5],[.5,.72],[.5,.28],[.3,.5],[.7,.5]]){const x=r.x+r.w*u,y=r.y+r.h*v,b={x:x-width/2,y:y-height/2,w:width,h:height};if(b.x<r.x+40||b.x+b.w>r.x+r.w-40||b.y<r.y+40||b.y+b.h>r.y+r.h-40)continue;if(!occupied.some(p=>p.x<b.x+b.w&&p.x+p.w>b.x&&p.y<b.y+b.h&&p.y+p.h>b.y))return [x,y];}return null;};
 const p=floor.pieces.find(p=>p.id===selected&&p.visible!==false);return <svg ref={svgRef} id="floor-plan" viewBox={view.join(' ')} xmlns="http://www.w3.org/2000/svg" tabIndex={0} aria-label={floor.name+'可编辑户型图'} onPointerDown={onBackground}>
 <defs><pattern id="planGrid" width="100" height="100" patternUnits="userSpaceOnUse"><path d="M100 0H0V100" fill="none" stroke="#b9cbd0" strokeWidth="3"/></pattern><pattern id="proposed" width="90" height="90" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><path d="M0 0V90" stroke="#b8763d" strokeWidth="12" opacity=".3"/></pattern></defs>
 <rect x="-100000" y="-100000" width="200000" height="200000" fill={grid?'url(#planGrid)':'#f3f6f7'}/>
 <polygon points={floor.outline.map(p=>p.join(',')).join(' ')} fill="#fffef9" stroke="#c7cfc7" strokeWidth="10"/>
 {original&&<polygon points={floor.originalOutline.map(p=>p.join(',')).join(' ')} fill="none" stroke="#bc8861" strokeDasharray="90 55" strokeWidth="16"/>}
 {floor.rooms.map(r=>{const at=roomLabel(r);return <g key={r.id} className="room-zone" pointerEvents="none"><rect x={r.x} y={r.y} width={r.w} height={r.h} fill={floor.id==='f2'?'#e7ddce':'transparent'} fillOpacity=".28"/>{at&&labels&&(floor.id==='f2'||['wc','entry','balcony'].includes(r.id))&&<text x={at[0]} y={at[1]} textAnchor="middle" className="room-label">{r.name}</text>}</g>;})}
 {floor.pieces.map(item=><g key={item.id} data-piece={item.id} onPointerDown={e=>{e.stopPropagation();onDown?.(e,item);}} className={'piece '+(item.type==='wall'?'wall-piece':'')}>
 {(original||item.visible===false)&&item.original&&changedPiece(item)&&<PieceDrawing p={{...item,...item.original,rotation:0}} floorId={floor.id} ghost/>}
 {item.visible!==false?item.type==='wall'&&scene?.valid?<g>{scene.shapes.filter(s=>s.kind==='wall'&&s.objectId===item.id).map(s=><polygon key={s.key} points={s.ring.map(p=>p.join(',')).join(' ')} fill={item.structural==='candidate'||item.structural==='confirmed'?'#334a50':'#959f9a'} stroke={selected===item.id?'#247da0':'#566964'} strokeWidth={selected===item.id?25:5}/>)}</g>:<PieceDrawing p={item} floorId={floor.id} selected={selected===item.id} labels={labels}/>:item.original&&<g className="removed-wall"><rect x={item.original.x} y={item.original.y} width={item.original.w} height={item.original.h} fill="url(#proposed)" stroke="#bd7046" strokeDasharray="35 30" strokeWidth="9"/></g>}
 </g>)}
 {p&&onResize&&<g transform={`translate(${p.x} ${p.y}) rotate(${p.rotation} ${p.w/2} ${p.h/2})`}><rect x={p.w-70} y={p.h-70} width="140" height="140" rx="18" fill="#fff" stroke="#267c9d" strokeWidth="23" className="resize-handle" data-resize="true" onPointerDown={e=>{e.stopPropagation();onResize(e,p);}}/></g>}
 {boundary&&floor.outline.map((q,i)=><g key={i}><circle cx={q[0]} cy={q[1]} r="82" fill="#fff" stroke="#287c99" strokeWidth="22" data-vertex={i} className="vertex" onPointerDown={e=>{e.stopPropagation();onVertex?.(e,i);}}/><text x={q[0]+105} y={q[1]-110} className="vertex-label">{i+1}</text></g>)}
 {measure&&measure.length===2&&<g pointerEvents="none"><path d={`M${measure[0].join(' ')}L${measure[1].join(' ')}`} stroke="#277c99" strokeWidth="18" strokeDasharray="65 30"/><circle cx={measure[0][0]} cy={measure[0][1]} r="42" fill="#277c99"/><circle cx={measure[1][0]} cy={measure[1][1]} r="42" fill="#277c99"/><text x={(measure[0][0]+measure[1][0])/2} y={(measure[0][1]+measure[1][1])/2-130} textAnchor="middle" className="measure-label">{Math.round(Math.hypot(measure[1][0]-measure[0][0],measure[1][1]-measure[0][1]))} mm</text></g>}
 {floor.pieces.filter(p=>p.visible!==false&&p.usage?.open&&p.usage.depth).flatMap(p=>pieceShapes(p).filter(s=>s.kind==='operation').map(s=><polygon key={s.key} points={s.ring.map(q=>q.join(',')).join(' ')} fill="#b9862e22" stroke="#b9862e" strokeWidth="15" strokeDasharray="60 40" pointerEvents="none"/>))}
 {scene?.shapes.filter(s=>s.key.includes(':filled:')).map(s=><polygon key={s.key} points={s.ring.map(p=>p.join(',')).join(' ')} fill="#959f9a" stroke="#b8763d" strokeWidth="15"/>)}
 {overlay}
 {previewWall&&<PieceDrawing p={previewWall} selected labels={false}/>}
 </svg>
}
