import {useEffect,useRef,useState} from 'react';
import {clone} from '../lib/model';
import {validateProject,type Project} from '../lib/project-model';
import {api,ApiError,downloadJson,type Envelope} from '../lib/project-client';
const RECOVERY='xian-home-v4-recovery';
export function useProject(role:'owner'|'viewer'){
 const [authExpired,setAuthExpired]=useState(false);const authExpiredRef=useRef(false);
 const [access,setAccess]=useState<Pick<Envelope,'publicView'|'staticSnapshot'|'exportedAt'>>({});const accessRef=useRef(access);
 const [project,setProject]=useState<Project|null>(null),[revision,setRevision]=useState(0),[status,setStatus]=useState('正在读取项目'),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[historySize,setHistorySize]=useState([0,0]);
 const data=useRef<Project|null>(null),rev=useRef(0),generation=useRef(0),saved=useRef(0),blocked=useRef(false),busy=useRef(false),timer=useRef<any>(null),past=useRef<Project[]>([]),future=useRef<Project[]>([]),inflight=useRef<{project:Project;baseRevision:number;operationId:string;generation:number}|null>(null),disposed=useRef(false);
 function display(p:Project){data.current=p;setProject(p);}
 function backup(){if(!data.current)return;try{localStorage.setItem(RECOVERY,JSON.stringify({project:data.current,baseRevision:rev.current,updatedAt:new Date().toISOString()}));}catch{setError('本机恢复空间不足，请立即下载完整备份。');}}
 function schedule(){clearTimeout(timer.current);timer.current=setTimeout(()=>void save(),800);}
 function checkRole(e:Envelope){if(role==='owner'&&e.role!=='owner'){authExpiredRef.current=true;setAuthExpired(true);blocked.current=true;clearTimeout(timer.current);backup();throw new ApiError('管理登录已失效，已暂停编辑与保存；请下载本机调整后重新登录。',401,{});}}
 function adopt(e:Envelope){checkRole(e);const nextAccess={publicView:e.publicView,staticSnapshot:e.staticSnapshot,exportedAt:e.exportedAt};accessRef.current=nextAccess;setAccess(nextAccess);display(e.project);rev.current=e.revision;setRevision(e.revision);generation.current=0;saved.current=0;inflight.current=null;blocked.current=false;setConflict(false);past.current=[];future.current=[];setHistorySize([0,0]);setStatus(role==='viewer'?(e.staticSnapshot?'发布于 '+new Date(e.exportedAt||'').toLocaleString('zh-CN'):e.publicView?'已连接当前方案 · 只读':'固定分享版本 · 只读'):'已保存到工作台');setError('');}
 async function reload(){try{const e:Envelope=await api('/project');if(!validateProject(e.project))throw Error('项目格式不正确，已有数据未被替换');adopt(e);if(role==='owner'){let recovery:any;try{recovery=JSON.parse(localStorage.getItem(RECOVERY)||'null');}catch{}if(recovery&&validateProject(recovery.project)&&JSON.stringify(recovery.project)===JSON.stringify(e.project))localStorage.removeItem(RECOVERY);if(recovery&&validateProject(recovery.project)&&JSON.stringify(recovery.project)!==JSON.stringify(e.project)){display(recovery.project);generation.current=1;if(recovery.baseRevision===e.revision){setStatus('已恢复本机未提交草稿');schedule();}else{blocked.current=true;setConflict(true);setStatus('本机草稿与服务器版本不同');}}}}catch(e){setError((e as Error).message);setStatus(authExpiredRef.current?'管理登录已失效 · 本机草稿保留':'服务未连接');}}
 async function save(){if(role!=='owner'||!data.current||blocked.current||busy.current)return false;if(generation.current===saved.current)return true;busy.current=true;setStatus('正在保存');if(!inflight.current)inflight.current={project:clone(data.current),baseRevision:rev.current,operationId:crypto.randomUUID(),generation:generation.current};const pending=inflight.current;
 try{const result:Envelope=await api('/project',{method:'PUT',body:JSON.stringify(pending)});rev.current=result.revision;setRevision(result.revision);saved.current=pending.generation;inflight.current=null;setError('');setStatus('已保存到工作台');if(generation.current===pending.generation){display(result.project);localStorage.removeItem(RECOVERY);}else{backup();schedule();}return true;}catch(e){const err=e as ApiError;if(err.status===401||err.status===403){authExpiredRef.current=true;setAuthExpired(true);blocked.current=true;backup();clearTimeout(timer.current);setStatus('管理登录已失效 · 本机草稿保留');setError('请下载本机调整后重新管理登录，当前修改没有覆盖服务器。');}else if(err.status===409){blocked.current=true;setConflict(true);inflight.current=null;setStatus('版本冲突 · 两份内容均保留');}else{setStatus('连接中断 · 草稿保留在本机');setError(err.message);clearTimeout(timer.current);timer.current=setTimeout(()=>void save(),7000);}return false;}finally{busy.current=false;}}
 function replace(next:Project,record=true){if(role!=='owner'||authExpiredRef.current)return;if(!validateProject(next)){setError('修改后的项目数据无效，已保留原方案');return;}if(record&&data.current){past.current.push(clone(data.current));if(past.current.length>40)past.current.shift();future.current=[];}display(next);generation.current++;setHistorySize([past.current.length,future.current.length]);setStatus(blocked.current?'冲突草稿 · 本机保留':'有未保存的修改');backup();if(!blocked.current)schedule();}
 function undo(){if(!past.current.length||!data.current)return;future.current.push(clone(data.current));replace(past.current.pop()!,false);setHistorySize([past.current.length,future.current.length]);}
 function redo(){if(!future.current.length||!data.current)return;past.current.push(clone(data.current));replace(future.current.pop()!,false);setHistorySize([past.current.length,future.current.length]);}
 async function resolveConflict(){if(!data.current)return;const local=clone(data.current),startGeneration=generation.current;try{const latest:Envelope=await api('/project');if(generation.current!==startGeneration)throw Error('本机草稿刚有新修改，请再次合并，所有内容仍保留。');downloadJson({project:local,baseRevision:rev.current,exportedAt:new Date().toISOString()},'合并前-完整本机冲突草稿.json');const next=clone(latest.project),mapping=new Map<string,string>(),stamp=new Date().toISOString();
 for(const v of local.variants){const remote=latest.project.variants.find(q=>q.id===v.id);if(!remote||JSON.stringify(remote.state)!==JSON.stringify(v.state)||remote.name!==v.name){const id=crypto.randomUUID();mapping.set(v.id,id);next.variants.push({...v,id,name:v.name+' · 本机冲突副本',updatedAt:stamp});}}
 for(const a of local.assets){const remote=next.assets.find(q=>q.id===a.id);if(!remote)next.assets.push({...a,variantId:a.variantId?(mapping.get(a.variantId)||a.variantId):undefined});else if(JSON.stringify(remote)!==JSON.stringify(a))next.issues.push({id:crypto.randomUUID(),title:'资料说明有本机冲突副本：'+a.name,note:'服务器说明已保留。本机资料说明如下，确认后可回填：\n'+JSON.stringify(a,null,2),floorId:a.floorId||'all',variantId:a.variantId?(mapping.get(a.variantId)||a.variantId):undefined,status:'open',createdAt:stamp});}
 for(const issue of local.issues){const remote=next.issues.find(q=>q.id===issue.id);if(!remote||JSON.stringify(remote)!==JSON.stringify(issue)||issue.variantId&&mapping.has(issue.variantId))next.issues.push({...issue,id:remote?crypto.randomUUID():issue.id,title:remote?issue.title+' · 本机副本':issue.title,variantId:issue.variantId?(mapping.get(issue.variantId)||issue.variantId):undefined});}
 for(const render of local.renders){const remote=next.renders.find(q=>q.id===render.id);if(!remote||JSON.stringify(remote)!==JSON.stringify(render)||mapping.has(render.variantId))next.renders.push({...render,id:remote?crypto.randomUUID():render.id,variantId:mapping.get(render.variantId)||render.variantId});}
 if(local.name!==latest.project.name)next.issues.push({id:crypto.randomUUID(),title:'项目名称存在本机修改',note:'本机名称：'+local.name+'；服务器名称：'+latest.project.name,floorId:'all',status:'open',createdAt:stamp});
 if(!validateProject(next))throw Error('合并内容超出项目限制；完整本机冲突草稿已下载，服务器未覆盖。');adopt(latest);replace(next);await save();}catch(e){setError((e as Error).message);}}

 useEffect(()=>{disposed.current=false;void reload();const poll=setInterval(async()=>{if((role!=='owner'&&(!accessRef.current.publicView||accessRef.current.staticSnapshot))||busy.current||blocked.current||disposed.current)return;try{const startRevision=rev.current,startGeneration=generation.current;const e:Envelope=await api('/project');checkRole(e);if(disposed.current||busy.current||startRevision!==rev.current||startGeneration!==generation.current)return;if(e.revision>rev.current){if(generation.current>saved.current){blocked.current=true;setConflict(true);setStatus('收到其他位置的修改，已保留本机草稿');}else adopt(e);}else if(role==='viewer'){setError('');setStatus('已连接当前方案 · 只读');}}catch(err){if(authExpiredRef.current){setError((err as Error).message);setStatus('管理登录已失效 · 本机草稿保留');}else if(role==='viewer'){setError('连接已中断，当前显示上次读取的方案；重新连接后会更新。');setStatus('离线 · 不是最新状态');}}},20000);const unload=(e:BeforeUnloadEvent)=>{if(generation.current>saved.current){backup();e.preventDefault();}};window.addEventListener('beforeunload',unload);return()=>{disposed.current=true;clearInterval(poll);clearTimeout(timer.current);window.removeEventListener('beforeunload',unload);};},[]);
 return {authExpired,access,project,revision,status,error,conflict,replace,save,reload,adopt,resolveConflict,undo,redo,historySize,setError,data,rev};
}
