import type {Floor} from './model';
import {bbox,edges,type Scene,type Dimension} from './geometry';
import type {Point} from './measurement-model';
import type {RouteResult} from './routes';
const text=(d:Dimension)=>d.status==='overlap'?'重叠':d.value===null?'待复核':`${d.estimated?'≈':''}${Math.round(d.value)} mm`;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
function download(data:Blob,name:string){const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function badgePositions(ds:Dimension[],unit:number){const boxes:{x:number;y:number}[]=[];return ds.map(d=>{const cx=(d.a[0]+d.b[0])/2,cy=(d.a[1]+d.b[1])/2;let x=cx,y=cy;for(let k=0;k<150;k++){const a=k*2.399963,r=Math.sqrt(k)*15*unit;x=cx+Math.cos(a)*r;y=cy+Math.sin(a)*r;if(!boxes.some(b=>Math.abs(b.x-x)<17*unit&&Math.abs(b.y-y)<15*unit))break;}boxes.push({x,y});return [x,y] as Point;});}
export function csvDrawing(f:Floor,ds:Dimension[],routes:RouteResult[],revision:number){const rows=[['楼层','方案版本','导出时间','名称','端点A X','端点A Y','端点B X','端点B Y','尺寸mm','口径','数值来源','备注','使用状态','几何状态']];const time=new Date().toISOString();for(const d of ds)rows.push([f.name,String(revision),time,d.name,...d.a.map(String),...d.b.map(String),d.value===null?'':String(Math.round(d.value)),d.axis,d.estimated?'估算':d.category==='size'?'方案外尺寸':'方案计算',d.note,d.objectIds.map(id=>{const p=f.pieces.find(p=>p.id===id);return p?.usage?p.name+' '+JSON.stringify(p.usage):'';}).filter(Boolean).join('；'),({ok:'正常',overlap:'重叠',contact:'接触',invalid:'待复核'}[d.status])]);for(const r of routes)rows.push([f.name,String(revision),time,r.name,'','','','',r.width===null?'':String(Math.round(r.width)),'通行包络',r.status,`${r.resolution} mm网格；${r.note}`,'',r.status]);return '\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');}
export function svgDrawing(f:Floor,scene:Scene,ds:Dimension[],routes:RouteResult[],revision:number,font?:string){const b=bbox(f.outline as Point[]),legendW=6100,width=b.w+legendW+1600,height=Math.max(b.h+2000,(ds.length+scene.rooms.length+routes.length+7)*190),x0=b.x-700,y0=b.y-950;let s=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x0} ${y0} ${width} ${height}" width="${Math.round(width/12)}" height="${Math.round(height/12)}"><style>${font?`@font-face{font-family:Microsoft YaHei;src:url(data:font/woff2;base64,${font})}`:''}text{font-family:Microsoft YaHei;fill:#2d4850;font-size:135px}</style><rect x="${x0}" y="${y0}" width="${width}" height="${height}" fill="white"/><text x="${b.x}" y="${b.y-530}" font-size="230">${escape(f.name)} · 尺寸方案 · V${revision}</text><text x="${b.x}" y="${b.y-290}">尺寸 mm / 面积 ㎡ · ${new Date().toLocaleString('zh-CN')} · 方案值，现场待复核</text>`;
 s+=`<polygon points="${f.outline.map(p=>p.join(',')).join(' ')}" fill="#f9faf7" stroke="#87969c" stroke-width="12"/>`;
 for(const p of scene.shapes.filter(p=>p.kind!=='opening'||f.pieces.find(q=>q.id===p.objectId)?.openingKind==='window'))s+=`<polygon data-object="${escape(p.objectId)}" points="${p.ring.map(q=>q.join(',')).join(' ')}" fill="${p.kind==='wall'?'#344b50':p.kind==='opening'?'#cbdde4':p.kind==='operation'?'#f5e9d2':'#dbcbae'}" stroke="#758982" stroke-width="10"/>`;
 for(const p of f.pieces.filter(p=>p.visible===false&&p.original)){const o=p.original!;s+=`<rect x="${o.x}" y="${o.y}" width="${o.w}" height="${o.h}" fill="none" stroke="#b77344" stroke-width="12" stroke-dasharray="60 35"/>`;}
 for(const r of routes)s+=`<polyline points="${r.points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#bc783d" stroke-width="20" stroke-dasharray="70 40"/>`;
 const lx=b.x+b.w+500,badges=badgePositions(ds,12);let ly=b.y;
 for(const [i,d] of ds.entries()){if(d.value!==null){s+=`<path d="M${d.a.join(' ')}L${d.b.join(' ')} M${(d.a[0]+d.b[0])/2} ${(d.a[1]+d.b[1])/2}L${badges[i].join(' ')}" fill="none" stroke="#287b99" stroke-width="10"/><circle cx="${badges[i][0]}" cy="${badges[i][1]}" r="83" fill="white" stroke="#287b99" stroke-width="9"/><text x="${badges[i][0]}" y="${badges[i][1]}" text-anchor="middle" dominant-baseline="central" font-size="100">${i+1}</text>`;}s+=`<text x="${lx}" y="${ly}">${escape(`${i+1}. ${d.name}：${text(d)}`)}</text>`;ly+=190;}
 for(const r of scene.rooms){s+=`<text x="${lx}" y="${ly}">${escape(`${r.name}：${r.polygon.length?r.area.toFixed(2)+'㎡ / 空地 '+r.freeArea.toFixed(2)+'㎡':r.status}`)}</text>`;ly+=190;}
 for(const r of routes){s+=`<text x="${lx}" y="${ly}">${escape(`${r.name}：${r.width===null?r.note:'≈'+Math.round(r.width)+'mm，'+r.resolution+'mm网格'}`)}</text>`;ly+=190;}
 return s+'</svg>';}
export function dxfDrawing(f:Floor,scene:Scene,ds:Dimension[],routes:RouteResult[],revision:number){let handle=256;const id=()=> (++handle).toString(16).toUpperCase();const pair=(c:number,v:string|number)=>`${c}\n${v}\n`;const point=(p:Point,code=10)=>pair(code,p[0])+pair(code+10,-p[1])+pair(code+20,0);const entity=(kind:string,layer:string,extra:string)=>pair(0,kind)+pair(5,id())+pair(100,'AcDbEntity')+pair(8,layer)+extra;let entities='',blocks='';
 const line=(a:Point,b:Point,layer='DIMENSIONS')=>entity('LINE',layer,pair(100,'AcDbLine')+point(a)+point(b,11));
 const txt=(value:string,p:Point,height=100,layer='LABELS')=>entity('TEXT',layer,pair(100,'AcDbText')+point(p)+pair(40,height)+pair(1,value.replace(/[\r\n]/g,' '))+pair(7,'YAHEI')+pair(100,'AcDbText'));
 const poly=(ring:Point[],layer:string,closed=true)=>entity('LWPOLYLINE',layer,pair(100,'AcDbPolyline')+pair(90,ring.length)+pair(70,closed?1:0)+ring.map(p=>pair(10,p[0])+pair(20,-p[1])).join(''));
 entities+=poly(f.outline as Point[],'BOUNDARY');
 for(const s of scene.shapes){const layer=s.kind==='wall'?'WALLS':s.kind==='opening'?'OPENINGS':s.kind==='operation'?'USE_RANGE':s.kind==='stair'?'STAIRS':'FURNITURE';entities+=poly(s.ring,layer);}
 for(const p of f.pieces.filter(p=>p.visible===false&&p.original)){const o=p.original!;entities+=poly([[o.x,o.y],[o.x+o.w,o.y],[o.x+o.w,o.y+o.h],[o.x,o.y+o.h]],'DEMOLITION');}
 for(const r of routes)if(r.points.length)entities+=poly(r.points,'ROUTES',false);
 const b=bbox(f.outline as Point[]);entities+=txt(`${f.name} / V${revision} / mm / ${new Date().toISOString()}`,[b.x,b.y-400],180);const blockNames:string[]=[];
 for(const [i,d] of ds.entries()){if(d.value===null){entities+=txt(`${i+1} ${d.name} 待复核`,[b.x+b.w+400,b.y+i*160]);continue;}const name='*D'+(i+1),center:Point=[(d.a[0]+d.b[0])/2,(d.a[1]+d.b[1])/2-120],label=`${i+1} ${text(d)}`;blockNames.push(name);blocks+=entity('BLOCK','DIMENSIONS',pair(100,'AcDbBlockBegin')+pair(2,name)+pair(70,1)+point([0,0])+pair(3,name)+pair(1,''))+line(d.a,d.b)+txt(label,center)+entity('ENDBLK','DIMENSIONS',pair(100,'AcDbBlockEnd'));
 entities+=entity('DIMENSION','DIMENSIONS',pair(100,'AcDbDimension')+pair(2,name)+point(d.b)+point(center,11)+pair(70,33)+pair(1,d.status==='overlap'?`${i+1} 重叠`:`${i+1} ${d.estimated?'≈':''}<> mm`)+pair(3,'HOME_MM')+pair(100,'AcDbAlignedDimension')+point(d.a,13)+point(d.b,14));entities+=txt(`${i+1}. ${d.name} = ${text(d)} (${d.estimated?'估算':'方案'})`,[b.x+b.w+400,b.y+i*160]);}
 const layers=['0','BOUNDARY','WALLS','OPENINGS','FURNITURE','STAIRS','DEMOLITION','USE_RANGE','DIMENSIONS','LABELS','ROUTES'];let tables=pair(0,'TABLE')+pair(2,'LTYPE')+pair(5,id())+pair(100,'AcDbSymbolTable')+pair(70,1)+pair(0,'LTYPE')+pair(5,id())+pair(100,'AcDbSymbolTableRecord')+pair(100,'AcDbLinetypeTableRecord')+pair(2,'CONTINUOUS')+pair(70,0)+pair(3,'Solid line')+pair(72,65)+pair(73,0)+pair(40,0)+pair(0,'ENDTAB');
 tables+=pair(0,'TABLE')+pair(2,'LAYER')+pair(5,id())+pair(100,'AcDbSymbolTable')+pair(70,layers.length)+layers.map((l,i)=>pair(0,'LAYER')+pair(5,id())+pair(100,'AcDbSymbolTableRecord')+pair(100,'AcDbLayerTableRecord')+pair(2,l)+pair(70,0)+pair(62,[7,8,7,4,3,8,1,2,5,7,2][i])+pair(6,'CONTINUOUS')).join('')+pair(0,'ENDTAB');
 const fontHandle=id();tables+=pair(0,'TABLE')+pair(2,'STYLE')+pair(5,id())+pair(100,'AcDbSymbolTable')+pair(70,1)+pair(0,'STYLE')+pair(5,fontHandle)+pair(100,'AcDbSymbolTableRecord')+pair(100,'AcDbTextStyleTableRecord')+pair(2,'YAHEI')+pair(70,0)+pair(40,0)+pair(41,1)+pair(50,0)+pair(71,0)+pair(42,100)+pair(3,'msyh.ttf')+pair(4,'')+pair(0,'ENDTAB');
 tables+=pair(0,'TABLE')+pair(2,'DIMSTYLE')+pair(5,id())+pair(100,'AcDbSymbolTable')+pair(70,1)+pair(0,'DIMSTYLE')+pair(105,id())+pair(100,'AcDbSymbolTableRecord')+pair(100,'AcDbDimStyleTableRecord')+pair(2,'HOME_MM')+pair(70,0)+pair(40,1)+pair(41,50)+pair(140,100)+pair(271,0)+pair(340,fontHandle)+pair(0,'ENDTAB');
 tables+=pair(0,'TABLE')+pair(2,'BLOCK_RECORD')+pair(5,id())+pair(100,'AcDbSymbolTable')+pair(70,blockNames.length)+blockNames.map(n=>pair(0,'BLOCK_RECORD')+pair(5,id())+pair(100,'AcDbSymbolTableRecord')+pair(100,'AcDbBlockTableRecord')+pair(2,n)+pair(70,0)).join('')+pair(0,'ENDTAB');
 return pair(0,'SECTION')+pair(2,'HEADER')+pair(9,'$ACADVER')+pair(1,'AC1027')+pair(9,'$INSUNITS')+pair(70,4)+pair(9,'$MEASUREMENT')+pair(70,1)+pair(0,'ENDSEC')+pair(0,'SECTION')+pair(2,'TABLES')+tables+pair(0,'ENDSEC')+pair(0,'SECTION')+pair(2,'BLOCKS')+blocks+pair(0,'ENDSEC')+pair(0,'SECTION')+pair(2,'ENTITIES')+entities+pair(0,'ENDSEC')+pair(0,'EOF');
}
let fontBytes:Promise<ArrayBuffer>|undefined;
async function fontData(){return fontBytes??=fetch('/fonts/yahei.ttf').then(r=>{if(!r.ok)throw Error('微软雅黑字体未加载');return r.arrayBuffer();});}
export async function pdfDrawing(f:Floor,scene:Scene,ds:Dimension[],routes:RouteResult[],revision:number){const {PDFDocument,rgb}=await import('pdf-lib'),fontkit=(await import('@pdf-lib/fontkit')).default;const doc=await PDFDocument.create();doc.registerFontkit(fontkit);const font=await doc.embedFont(await fontData(),{subset:true});doc.setTitle(f.name+'尺寸方案');doc.setSubject('毫米尺寸方案；现场待复核');const W=1190.55,H=841.89,ink=rgb(.15,.26,.3),blue=rgb(.16,.45,.57),b=bbox(f.outline as Point[]),margin=42,scale=Math.min(72/25.4/50,(W-margin*2)/(b.w+1700),(H-145)/(b.h+1300));
 const page=doc.addPage([W,H]),xy=(p:Point):Point=>[margin+650*scale+(p[0]-b.x)*scale,H-100-(p[1]-b.y)*scale],label=(v:string,x:number,y:number,size=10)=>page.drawText(v,{x,y,size,font,color:ink});label(`${f.name} · 尺寸平面`,margin,H-40,19);label(`方案 V${revision} · ${new Date().toLocaleString('zh-CN')} · 单位 mm / ㎡ · 标注编号见后页`,margin,H-60,10);
 function line(a:Point,c:Point,color=blue,width=.55){const p=xy(a),q=xy(c);page.drawLine({start:{x:p[0],y:p[1]},end:{x:q[0],y:q[1]},thickness:width,color});}
 for(const s of scene.shapes){const color=s.kind==='wall'?rgb(.2,.28,.3):s.kind==='operation'?rgb(.69,.48,.22):rgb(.48,.55,.51);for(const [a,c] of edges(s.ring))line(a,c,color,s.kind==='wall'?1.2:.55);}
 for(const [a,c] of edges(f.outline as Point[]))line(a,c,ink,.7);
 const badges=badgePositions(ds,1/scale);for(const [i,d] of ds.entries())if(d.value!==null){line(d.a,d.b);line([(d.a[0]+d.b[0])/2,(d.a[1]+d.b[1])/2],badges[i],blue,.3);const p=xy(badges[i]);page.drawCircle({x:p[0],y:p[1],size:6.5,color:rgb(1,1,1),borderColor:blue,borderWidth:.4});const value=String(i+1);label(value,p[0]-font.widthOfTextAtSize(value,6)/2,p[1]-2,6);}
 for(const r of routes)for(let i=1;i<r.points.length;i++)line(r.points[i-1],r.points[i],rgb(.73,.45,.23),1);
 label(`外轮廓含墙 ${scene.outerArea.toFixed(2)} ㎡ · 扣墙地面 ${scene.netArea.toFixed(2)} ㎡ · 剩余空地 ${scene.emptyArea.toFixed(2)} ㎡`,margin,38,10);label(`比例尺见图；A3以实际大小打印。`,margin,22,9);const p0=xy([b.x,b.y+b.h+430]),p1=xy([b.x+2000,b.y+b.h+430]);page.drawLine({start:{x:p0[0],y:p0[1]},end:{x:p1[0],y:p1[1]},thickness:2,color:ink});label('0                         2000 mm',p0[0],p0[1]-13,9);
 const rows=ds.map((d,i)=>[`${i+1}`,d.name,text(d),d.estimated?'估算':'方案计算',d.note]);for(const r of scene.rooms)rows.push(['区域',r.name,r.polygon.length?r.area.toFixed(2)+'㎡':'待复核','净面积',r.polygon.length?`空地${r.freeArea.toFixed(2)}㎡；范围${Math.round(r.width)}×${Math.round(r.depth)}mm；${r.status}`:r.status]);for(const r of routes)rows.push(['路线',r.name,r.width===null?'未连通':'≈'+Math.round(r.width)+'mm','通行估算',`${r.resolution}mm网格；目标${r.target}mm；${r.note}`]);
 for(let start=0;start<rows.length;start+=28){const p=doc.addPage([W,H]);p.drawText(`${f.name} · 尺寸与空间清单 ${Math.floor(start/28)+1}`,{x:margin,y:H-45,size:18,font,color:ink});const cols=[margin,margin+50,margin+370,margin+485,margin+575];['编号','测量关系 / 区域','数值','口径','备注'].forEach((t,i)=>p.drawText(t,{x:cols[i],y:H-78,size:11,font,color:blue}));for(const [k,row] of rows.slice(start,start+28).entries()){const y=H-108-k*24;row.forEach((v,i)=>{let size=10;const max=i===0?45:i===1?310:i===2?110:i===3?85:W-cols[4]-margin;while(font.widthOfTextAtSize(v,size)>max&&size>7)size-=.3;p.drawText(v,{x:cols[i],y,size,font,color:ink});});p.drawLine({start:{x:margin,y:y-8},end:{x:W-margin,y:y-8},thickness:.3,color:rgb(.84,.88,.88)});}p.drawText('尺寸由当前平面计算；估算、原图参考和现场复核值不可混用。',{x:margin,y:30,size:10,font,color:ink});}
 return doc.save();}
export async function exportDrawing(kind:'svg'|'pdf'|'dxf'|'csv',f:Floor,scene:Scene,ds:Dimension[],routes:RouteResult[],revision:number){if(!scene.valid)throw Error(scene.error);let blob:Blob;if(kind==='pdf')blob=new Blob([await pdfDrawing(f,scene,ds,routes,revision) as BlobPart],{type:'application/pdf'});else if(kind==='dxf')blob=new Blob([dxfDrawing(f,scene,ds,routes,revision)],{type:'application/dxf'});else if(kind==='csv')blob=new Blob([csvDrawing(f,ds,routes,revision)],{type:'text/csv;charset=utf-8'});else{const font=await fetch('/fonts/yahei-full.woff2').then(r=>r.arrayBuffer());let base64='';const bytes=new Uint8Array(font);for(let i=0;i<bytes.length;i+=8192)base64+=String.fromCharCode(...bytes.subarray(i,i+8192));blob=new Blob([svgDrawing(f,scene,ds,routes,revision,btoa(base64))],{type:'image/svg+xml'});}download(blob,`${f.name}-尺寸方案-V${revision}.${kind}`);}
