import pc from 'polygon-clipping';
import type {Floor,Piece} from './model';
import {activeParts,rectRing,type Point,type Ring,type Anchor,type MeasureSpec} from './measurement-model';
export type Multi=Point[][][];
export type Shape={key:string;objectId:string;partId:string;name:string;ring:Ring;kind:string;estimated:boolean;operation?:boolean};
export type Dimension={id:string;name:string;a:Point;b:Point;value:number|null;status:'ok'|'contact'|'overlap'|'invalid';axis:string;estimated:boolean;note:string;objectIds:string[];spec?:MeasureSpec;category:'size'|'gap'|'relation'};
export type AreaResult={id:string;name:string;polygon:Multi;area:number;freeArea:number;width:number;depth:number;status:string;sourceArea?:number};
export type Scene={shapes:Shape[];obstacles:Multi;floorFree:Multi;walking:Multi;rooms:AreaResult[];outerArea:number;netArea:number;emptyArea:number;valid:boolean;error?:string};
export const EPS=.01;
export const dist=(a:Point,b:Point)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
export const mid=(a:Point,b:Point):Point=>[(a[0]+b[0])/2,(a[1]+b[1])/2];
export function toWorld(p:Piece,q:Point):Point{const x=q[0]*p.w/(p.baseW||p.w)-p.w/2,y=q[1]*p.h/(p.baseH||p.h)-p.h/2,a=p.rotation*Math.PI/180;return [p.x+p.w/2+x*Math.cos(a)-y*Math.sin(a),p.y+p.h/2+x*Math.sin(a)+y*Math.cos(a)];}
export function toLocal(p:Piece,q:Point):Point{const a=-p.rotation*Math.PI/180,x=q[0]-p.x-p.w/2,y=q[1]-p.y-p.h/2;return [(x*Math.cos(a)-y*Math.sin(a)+p.w/2)*(p.baseW||p.w)/p.w,(x*Math.sin(a)+y*Math.cos(a)+p.h/2)*(p.baseH||p.h)/p.h];}
export function pieceShapes(p:Piece):Shape[]{if(p.visible===false||p.type==='zone')return [];const parts=activeParts(p);const shapes:Shape[]=parts.map(part=>({key:p.id+':'+part.id,objectId:p.id,partId:part.id,name:part.name,ring:part.ring.map(q=>toWorld(p,q)),kind:p.type,estimated:!!part.estimated}));
 if(p.usage?.open&&p.usage.depth){const w=p.baseW||p.w,h=p.baseH||p.h,side=p.usage.side||'bottom',d=p.usage.depth*(side==='left'||side==='right'?w/p.w:h/p.h);const ring=side==='top'?rectRing(0,-d,w,d):side==='left'?rectRing(-d,0,d,h):side==='right'?rectRing(w,0,d,h):rectRing(0,h,w,d);shapes.push({key:p.id+':operation',objectId:p.id,partId:'operation',name:p.name+'开启范围',ring:ring.map(q=>toWorld(p,q)),kind:'operation',estimated:true});}
 return shapes;
}
export function ringArea(r:Ring){return Math.abs(r.reduce((v,a,i)=>{const b=r[(i+1)%r.length];return v+a[0]*b[1]-b[0]*a[1];},0))/2;}
export const multiArea=(m:Multi)=>m.reduce((s,p)=>s+ringArea(p[0])-p.slice(1).reduce((v,r)=>v+ringArea(r),0),0);
export function bbox(r:Ring){const x=Math.min(...r.map(p=>p[0])),y=Math.min(...r.map(p=>p[1]));return {x,y,w:Math.max(...r.map(p=>p[0]))-x,h:Math.max(...r.map(p=>p[1]))-y};}
export function pointInRing(q:Point,r:Ring){let yes=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const a=r[i],b=r[j];if((a[1]>q[1])!==(b[1]>q[1])&&q[0]<(b[0]-a[0])*(q[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
export const pointInMulti=(q:Point,m:Multi)=>m.some(p=>pointInRing(q,p[0])&&!p.slice(1).some(r=>pointInRing(q,r)));
export const edges=(r:Ring):[Point,Point][]=>r.map((p,i)=>[p,r[(i+1)%r.length]]);
const boxesOverlap=(a:ReturnType<typeof bbox>,b:ReturnType<typeof bbox>,strict=false)=>strict?Math.min(a.x+a.w,b.x+b.w)>Math.max(a.x,b.x)+EPS&&Math.min(a.y+a.h,b.y+b.h)>Math.max(a.y,b.y)+EPS:Math.min(a.x+a.w,b.x+b.w)>=Math.max(a.x,b.x)-EPS&&Math.min(a.y+a.h,b.y+b.h)>=Math.max(a.y,b.y)-EPS;
const cross=(a:Point,b:Point,c:Point)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
export function segmentsIntersect(a:Point,b:Point,c:Point,d:Point){const ab1=cross(a,b,c),ab2=cross(a,b,d),cd1=cross(c,d,a),cd2=cross(c,d,b);return ab1*ab2<=EPS&&cd1*cd2<=EPS&&Math.max(Math.min(a[0],b[0]),Math.min(c[0],d[0]))<=Math.min(Math.max(a[0],b[0]),Math.max(c[0],d[0]))+EPS&&Math.max(Math.min(a[1],b[1]),Math.min(c[1],d[1]))<=Math.min(Math.max(a[1],b[1]),Math.max(c[1],d[1]))+EPS;}
export function simpleRing(input:Ring){const r=input.filter((p,i)=>i===0||dist(p,input[i-1])>EPS);if(r.length>1&&dist(r[0],r.at(-1)!)<EPS)r.pop();if(r.length<3||ringArea(r)<1||r.some(q=>!q.every(Number.isFinite)))return false;const n=r.length;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){if(j===i+1||i===0&&j===n-1)continue;if(segmentsIntersect(r[i],r[(i+1)%n],r[j],r[(j+1)%n]))return false;}return true;}
export function project(q:Point,a:Point,b:Point):Point{const l=(b[0]-a[0])**2+(b[1]-a[1])**2,t=l?Math.max(0,Math.min(1,((q[0]-a[0])*(b[0]-a[0])+(q[1]-a[1])*(b[1]-a[1]))/l)):0;return [a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])];}
export function segmentDistance(a:Point,b:Point,c:Point,d:Point):[Point,Point,number]{if(segmentsIntersect(a,b,c,d)){const den=(a[0]-b[0])*(c[1]-d[1])-(a[1]-b[1])*(c[0]-d[0]);if(Math.abs(den)>EPS){const t=((a[0]-c[0])*(c[1]-d[1])-(a[1]-c[1])*(c[0]-d[0]))/den;const p:Point=[a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])];return [p,p,0];}}
 const cs:[Point,Point][]=[[a,project(a,c,d)],[b,project(b,c,d)],[project(c,a,b),c],[project(d,a,b),d]];cs.sort((x,y)=>dist(...x)-dist(...y));return [...cs[0],dist(...cs[0])];}
export function union(rings:Ring[]):Multi{return rings.length?pc.union(...rings.map(r=>[r]) as [any,...any[]]) as Multi:[];}
export const difference=(a:Multi,b:Multi):Multi=>!a.length?[]:!b.length?a:pc.difference(a,b) as Multi;
export const intersection=(a:Multi,b:Multi):Multi=>!a.length||!b.length?[]:pc.intersection(a,b) as Multi;
function clean(r:Ring){return r.length>1&&dist(r[0],r.at(-1)!)<EPS?r.slice(0,-1):r;}
export function wallShapes(f:Floor,raw:Shape[]){const openings=f.pieces.filter(p=>p.visible!==false&&p.type==='opening'&&p.openingKind!=='window');const output:Shape[]=[];
 for(const shape of raw.filter(s=>s.kind==='wall')){const holes=openings.filter(p=>p.hostWallIds?.includes(shape.objectId)).flatMap(p=>pieceShapes(p).filter(q=>q.kind!=='operation').map(q=>q.ring));const polys=difference([[shape.ring]],union(holes));for(const [i,poly] of polys.entries())output.push({...shape,key:shape.key+':'+i,ring:clean(poly[0])});}
 // Moving an original opening fills its former span, then cuts the new span only in associated walls.
 for(const p of openings){const o=p.apertureOriginal;if(!o||!p.hostWallIds?.length||[p.x-o.x,p.y-o.y,p.w-o.w,p.h-o.h,p.rotation-o.rotation].every(v=>Math.abs(v)<EPS))continue;for(const old of pieceShapes({...p,...o,usage:undefined})){const remainder=difference([[old.ring]],union(pieceShapes(p).map(s=>s.ring)));for(const [i,poly] of remainder.entries())output.push({...old,key:p.id+':filled:'+i,objectId:p.id,name:p.name+'原洞封补',kind:'wall',ring:clean(poly[0]),estimated:true});}}
 return output;
}
export function computeScene(f:Floor):Scene{const invalid={shapes:[],obstacles:[],floorFree:[],walking:[],rooms:[],outerArea:0,netArea:0,emptyArea:0,valid:false} as Scene;
 const outline=f.outline as Ring;if(!simpleRing(outline))return {...invalid,error:'轮廓未闭合或自交，请先修复；面积与路线已停用。'};
 try{const raw=f.pieces.flatMap(pieceShapes),walls=wallShapes(f,raw),windows=raw.filter(s=>s.kind==='opening'&&f.pieces.find(p=>p.id===s.objectId)?.openingKind==='window'),solid=raw.filter(s=>['furniture','stair','operation'].includes(s.kind));const shapes=[...walls,...windows,...raw.filter(s=>s.kind!=='wall'&&!windows.includes(s))];
 const structural=union([...walls,...windows].map(s=>s.ring)),floorFree=difference([[outline]],structural),obstacles=union([...walls,...windows,...solid].map(s=>s.ring)),walking=difference([[outline]],obstacles);
 const roomClosures=raw.filter(s=>s.kind==='opening'&&!windows.includes(s)).map(s=>s.ring);const closed=difference(floorFree,union(roomClosures));const rooms:AreaResult[]=[];const used=new Map<number,AreaResult>();
 for(const r of f.rooms){if(r.name==='楼梯')continue;const center:Point=[r.x+r.w/2,r.y+r.h/2];let index=closed.findIndex(poly=>pointInMulti(center,[poly]));if(index<0){rooms.push({id:r.id,name:r.name,polygon:[],area:0,freeArea:0,width:0,depth:0,status:'边界待确认',sourceArea:(r as any).area});continue;}
  if(used.has(index)){const old=used.get(index)!;old.name+=' / '+r.name;old.status='连通开放区域';continue;}
  const poly=[closed[index]],b=bbox(poly[0][0]);const result={id:r.id,name:r.name,polygon:poly,area:multiArea(poly)/1e6,freeArea:multiArea(intersection(poly,walking))/1e6,width:b.w,depth:b.h,status:'墙体及洞口闭合计算',sourceArea:(r as any).area};used.set(index,result);rooms.push(result);
 }
 for(const r of f.regions||[]){if(!r.closed||!simpleRing(r.points)){rooms.push({id:r.id,name:r.name,polygon:[],area:0,freeArea:0,width:0,depth:0,status:'圈定区域未闭合或自交'});continue;}const poly=intersection([[r.points]],floorFree),b=bbox(r.points);rooms.push({id:r.id,name:r.name,polygon:poly,area:multiArea(poly)/1e6,freeArea:multiArea(intersection(poly,walking))/1e6,width:b.w,depth:b.h,status:'手动圈定区域'});}
 return {shapes,obstacles,floorFree,walking,rooms,outerArea:ringArea(outline)/1e6,netArea:multiArea(floorFree)/1e6,emptyArea:multiArea(walking)/1e6,valid:true};
 }catch{return {...invalid,error:'几何计算失败，请检查重叠墙段和边界节点。'};}}
const featureCache=new WeakMap<Floor,Map<string,Feature|null>>();
type Feature={lines:[Point,Point][];rings:Ring[];estimated:boolean;ids:string[]};
export function anchorFeature(f:Floor,a:Anchor):Feature|null{if(a.kind==='boundary')return buildAnchorFeature(f,a);let map=featureCache.get(f);if(!map){map=new Map();featureCache.set(f,map);}const key=JSON.stringify(a);if(map.has(key))return map.get(key)!;const result=buildAnchorFeature(f,a);map.set(key,result);return result;}
function buildAnchorFeature(f:Floor,a:Anchor):Feature|null{if(a.kind==='boundary'){const edge=edges(f.outline as Ring)[a.edge];return edge?{lines:[edge],rings:[],estimated:false,ids:[]}:null;}if(a.kind==='point')return {lines:[[a.point,a.point]],rings:[],estimated:false,ids:[]};const p=f.pieces.find(p=>p.id===a.objectId&&p.visible!==false);if(!p)return null;if(a.kind==='local'){const q=toWorld(p,a.point);return {lines:[[q,q]],rings:[],estimated:true,ids:[p.id]};}const parts=pieceShapes(p).filter(s=>s.kind!=='operation'&&(!a.partId||s.partId===a.partId));if(!parts.length)return null;const lines=parts.flatMap(s=>a.edge===undefined?edges(s.ring):[edges(s.ring)[a.edge]].filter(Boolean));return {lines,rings:a.edge===undefined?parts.map(s=>s.ring):[],estimated:parts.some(s=>s.estimated),ids:[p.id]};}
export function anchorPoint(f:Floor,a:Anchor):Point|null{const feature=anchorFeature(f,a);if(!feature?.lines.length)return null;if((a.kind==='object'||a.kind==='boundary')&&a.edge!==undefined){const [x,y]=feature.lines[0],t=a.t??.5;return [x[0]+t*(y[0]-x[0]),x[1]+t*(y[1]-x[1])];}const points=feature.lines.flat();const b=bbox(points);return [b.x+b.w/2,b.y+b.h/2];}
function axisPair(a:Point,b:Point,c:Point,d:Point,axis:number):[Point,Point,number]|null{const other=1-axis;const lo=Math.max(Math.min(a[other],b[other]),Math.min(c[other],d[other])),hi=Math.min(Math.max(a[other],b[other]),Math.max(c[other],d[other]));if(lo>hi+EPS)return null;const at=(p:Point,q:Point,t:number):Point=>{if(Math.abs(q[other]-p[other])<EPS)return mid(p,q);const n=(t-p[other])/(q[other]-p[other]);return [p[0]+n*(q[0]-p[0]),p[1]+n*(q[1]-p[1])];};const vals=[(lo+hi)/2,lo,hi].map(t=>{const p=at(a,b,t),q=at(c,d,t);return [p,q,dist(p,q)] as [Point,Point,number];});return vals.sort((x,y)=>x[2]-y[2])[0];}
export function measureSpec(f:Floor,spec:MeasureSpec,scene?:Scene):Dimension{if(spec.sizeId&&'objectId'in spec.a){const objectId=spec.a.objectId;const p=f.pieces.find(p=>p.id===objectId&&p.visible!==false);if(p){const d=sizeDimensions(p).find(d=>d.id===spec.sizeId);if(d)return {...d,id:spec.id,name:spec.name,spec};}}const a=anchorFeature(f,spec.a),b=anchorFeature(f,spec.b);const empty:Dimension={id:spec.id,name:spec.name,a:[0,0],b:[0,0],value:null,status:'invalid',axis:spec.mode,estimated:false,note:'测量端点已删除或当前状态不可用',objectIds:[],spec,category:'relation'};if(!a||!b)return empty;let best:[Point,Point,number]=[[0,0],[0,0],Infinity];let overlap=false;try{overlap=a.rings.length>0&&b.rings.length>0&&boxesOverlap(bbox(a.lines.flat()),bbox(b.lines.flat()),true)&&multiArea(intersection(union(a.rings),union(b.rings)))>EPS;}catch{}
 if(spec.mode==='direct'){const p=anchorPoint(f,spec.a)!,q=anchorPoint(f,spec.b)!;best=[p,q,dist(p,q)];}else for(const [a1,a2] of a.lines)for(const [b1,b2] of b.lines){const v=spec.mode==='shortest'?segmentDistance(a1,a2,b1,b2):axisPair(a1,a2,b1,b2,spec.mode==='horizontal'?0:1);if(v&&v[2]<best[2])best=v;}
 if(!Number.isFinite(best[2]))return {...empty,note:'投影未正对，可改用最短净距'};
 const ids=Array.from(new Set([...a.ids,...b.ids]));const lineBox=bbox([best[0],best[1]]);const obstructed=scene?.shapes.some(s=>!ids.includes(s.objectId)&&boxesOverlap(lineBox,bbox(s.ring))&&s.kind!=='opening'&&s.kind!=='operation'&&(pointInRing(mid(best[0],best[1]),s.ring)||edges(s.ring).some(([x,y])=>{const d=segmentDistance(best[0],best[1],x,y);return d[2]<EPS&&dist(d[0],best[0])>EPS&&dist(d[0],best[1])>EPS;})));
 return {...empty,a:best[0],b:best[1],value:overlap?0:best[2],status:overlap?'overlap':best[2]<EPS?'contact':'ok',estimated:a.estimated||b.estimated,objectIds:ids,note:obstructed?'中间有障碍，仅表示对象关系距离':a.estimated||b.estimated?'按外包轮廓／可调锚点估算':'方案几何计算'};
}
function sizeDimensions(p:Piece):Dimension[]{if(p.type==='opening'&&p.parts?.length){return pieceShapes(p).filter(s=>s.kind==='opening').flatMap((s,i)=>[0,1].map(edge=>{const a=s.ring[edge],b=s.ring[(edge+1)%s.ring.length];return {id:'size:'+p.id+':'+i+':'+edge,name:s.name+(edge?' 深／高':' 宽／厚'),a,b,value:dist(a,b),status:'ok' as const,axis:edge?'depth':'width',estimated:!!p.source?.includes('待复核'),note:'门窗实体边缘尺寸，非图形包围框',objectIds:[p.id],category:'size' as const};}));}const bw=p.baseW||p.w,bh=p.baseH||p.h,top=[toWorld(p,[0,0]),toWorld(p,[bw+(p.usage?.table==='extended'?600:0),0])] as [Point,Point],side=[toWorld(p,[bw,0]),toWorld(p,[bw,bh])] as [Point,Point];return [top,side].map(([a,b],i)=>({id:'size:'+p.id+':'+i,name:p.name+(i?' 深／厚':' 长／宽'),a,b,value:dist(a,b),status:'ok',axis:i?'depth':'width',estimated:!!p.source?.includes('待复核'),note:p.type==='opening'?'洞口几何尺寸；原图与现场另行核对':'方案外尺寸',objectIds:[p.id],category:'size'}));}
export function dimensionsFor(f:Floor,scene:Scene,selected:string,all:boolean):Dimension[]{const result:Dimension[]=[];const visible=f.pieces.filter(p=>p.visible!==false&&p.type!=='zone');const targets=all?visible:visible.filter(p=>p.id===selected);const dedup=new Set<string>();if(all)for(const [i,[a,b]] of edges(f.outline as Ring).entries()){if(dist(a,b)<EPS)continue;const spec:MeasureSpec={id:'boundary:'+i,name:'外轮廓边 '+(i+1),a:{kind:'boundary',edge:i,t:0},b:{kind:'boundary',edge:i,t:1},mode:'direct',pinned:false};result.push({...measureSpec(f,spec),category:'size'});}
 for(const p of targets){result.push(...sizeDimensions(p));if(all&&['wall','opening'].includes(p.type))continue;const candidates:{d:Dimension;direction:string}[]=[];for(const q of visible){if(q.id===p.id||q.type==='opening'&&q.openingKind!=='window')continue;const dx=q.x+q.w/2-p.x-p.w/2,dy=q.y+q.h/2-p.y-p.h/2;if(Math.hypot(dx,dy)>9000)continue;for(const mode of ['horizontal','vertical','shortest'] as const){const spec:MeasureSpec={id:`gap:${[p.id,q.id].sort().join(':')}:${mode}`,name:p.name+' → '+q.name,a:{kind:'object',objectId:p.id},b:{kind:'object',objectId:q.id},mode,pinned:false};const d=measureSpec(f,spec);if(d.value!==null&&d.value<5000)candidates.push({d:{...d,category:'gap'},direction:mode==='horizontal'?(dx<0?'left':'right'):mode==='vertical'?(dy<0?'top':'bottom'):'closest'});}}
  for(const direction of ['left','right','top','bottom','closest']){const choices=candidates.filter(c=>c.direction===direction).sort((a,b)=>a.d.value!-b.d.value!);for(const c of choices){const d={...measureSpec(f,c.d.spec!,scene),category:'gap' as const};if(d.note.startsWith('中间有障碍'))continue;if(!dedup.has(d.id)){result.push(d);dedup.add(d.id);}break;}}
 }
 for(const s of f.measurements||[]){if(all||s.pinned||[s.a,s.b].some(a=>'objectId'in a&&a.objectId===selected)){const d=measureSpec(f,s,scene);const i=result.findIndex(x=>x.id===s.id);if(i>=0)result[i]=d;else result.push(d);}}
 return result;
}
export function nearestAnchor(f:Floor,q:Point,objectId?:string,edge=false):Anchor{const candidates=f.pieces.filter(p=>p.visible!==false&&(!objectId||p.id===objectId)).flatMap(p=>pieceShapes(p).filter(s=>s.kind!=='operation').flatMap(s=>edges(s.ring).map(([a,b],i)=>({p,s,i,point:project(q,a,b),distance:dist(q,project(q,a,b))})))).sort((a,b)=>a.distance-b.distance);const c=candidates[0];if(!objectId){const boundary=edges(f.outline as Ring).map(([a,b],i)=>({i,point:project(q,a,b),distance:dist(q,project(q,a,b)),a,b})).sort((a,b)=>a.distance-b.distance)[0];if(boundary&&boundary.distance<120&&(!c||boundary.distance<c.distance))return {kind:'boundary',edge:boundary.i,t:edge?.5:dist(boundary.a,boundary.point)/(dist(boundary.a,boundary.b)||1)};}if(c&&(objectId||c.distance<120)){if(edge)return {kind:'object',objectId:c.p.id,partId:c.s.partId,edge:c.i};return {kind:'local',objectId:c.p.id,point:toLocal(c.p,c.point)};}return {kind:'point',point:q};}
