import {bbox,pointInMulti,pointInRing,segmentsIntersect,edges,toWorld,type Multi} from './geometry';
import type {Floor} from './model';
import type {Point,Ring} from './measurement-model';
export type RouteRequest={id:string;name:string;points:Point[];target:number;automatic?:boolean;targetBox?:{x:number;y:number;w:number;h:number}};
export type RouteResult={id:string;name:string;points:Point[];bottleneck?:Point;width:number|null;target:number;length:number;status:'ok'|'narrow'|'borderline'|'blocked'|'invalid'|'unrated';note:string;resolution:number};
export type RouteInput={requestId:number;floorId:string;free:Multi;outline:Ring;requests:RouteRequest[];resolution:number};
class Heap{ids:number[]=[];values:number[]=[];push(id:number,value:number){let i=this.ids.length;this.ids.push(id);this.values.push(value);while(i>0){const p=(i-1)>>1;if(this.values[p]>=value)break;this.ids[i]=this.ids[p];this.values[i]=this.values[p];i=p;}this.ids[i]=id;this.values[i]=value;}pop():[number,number]{const out:[number,number]=[this.ids[0],this.values[0]],id=this.ids.pop()!,v=this.values.pop()!;if(this.ids.length){let i=0;while(i*2+1<this.ids.length){let c=i*2+1;if(c+1<this.ids.length&&this.values[c+1]>this.values[c])c++;if(this.values[c]<=v)break;this.ids[i]=this.ids[c];this.values[i]=this.values[c];i=c;}this.ids[i]=id;this.values[i]=v;}return out;}}
function edt1(f:Float32Array,n:number,out:Float32Array,v:Int32Array,z:Float64Array){let k=0;v[0]=0;z[0]=-Infinity;z[1]=Infinity;for(let q=1;q<n;q++){let s=((f[q]+q*q)-(f[v[k]]+v[k]*v[k]))/(2*q-2*v[k]);while(s<=z[k]&&k>0){k--;s=((f[q]+q*q)-(f[v[k]]+v[k]*v[k]))/(2*q-2*v[k]);}k++;v[k]=q;z[k]=s;z[k+1]=Infinity;}k=0;for(let q=0;q<n;q++){while(z[k+1]<q)k++;out[q]=(q-v[k])**2+f[v[k]];}}
export function analyzeRoutes(input:RouteInput){const b=bbox(input.outline);let step=input.resolution;while((Math.ceil(b.w/step)+4)*(Math.ceil(b.h/step)+4)>2000000)step+=5;const ox=b.x-step*2,oy=b.y-step*2,w=Math.ceil(b.w/step)+4,h=Math.ceil(b.h/step)+4,N=w*h,open=new Uint8Array(N);
 // Scanline parity works for outer rings and holes. Boundary-touching cells are then conservatively blocked.
 for(let row=1;row<h-1;row++){const y=oy+(row+.5)*step;for(const poly of input.free){const xs:number[]=[];for(const r of poly)for(let j=0,i=r.length-1;j<r.length;i=j++){const a=r[i],c=r[j];if((a[1]>y)!==(c[1]>y))xs.push(a[0]+(y-a[1])*(c[0]-a[0])/(c[1]-a[1]));}xs.sort((a,b)=>a-b);for(let k=0;k+1<xs.length;k+=2){const start=Math.max(1,Math.ceil((xs[k]-ox)/step-.5)),end=Math.min(w-2,Math.floor((xs[k+1]-ox)/step-.5));for(let col=start;col<=end;col++)open[row*w+col]=1;}}}
 for(const poly of input.free)for(const r of poly)for(let i=0;i<r.length;i++){const a=r[i],c=r[(i+1)%r.length],n=Math.max(1,Math.ceil(Math.hypot(c[0]-a[0],c[1]-a[1])/(step*.35)));let lastX=-1,lastY=-1;for(let j=0;j<=n;j++){const x=Math.floor((a[0]+(c[0]-a[0])*j/n-ox)/step),y=Math.floor((a[1]+(c[1]-a[1])*j/n-oy)/step);if(x>=0&&y>=0&&x<w&&y<h){open[y*w+x]=0;if(lastX>=0&&lastY>=0&&lastX!==x&&lastY!==y){open[lastY*w+x]=0;open[y*w+lastX]=0;}lastX=x;lastY=y;}}}
 const field=new Float32Array(N),size=Math.max(w,h),f=new Float32Array(size),out=new Float32Array(size),v=new Int32Array(size),z=new Float64Array(size+1);for(let x=0;x<w;x++){for(let y=0;y<h;y++)f[y]=open[y*w+x]?1e12:0;edt1(f,h,out,v,z);for(let y=0;y<h;y++)field[y*w+x]=out[y];}for(let y=0;y<h;y++){for(let x=0;x<w;x++)f[x]=field[y*w+x];edt1(f,w,out,v,z);for(let x=0;x<w;x++)field[y*w+x]=Math.max(0,Math.sqrt(out[x])*step-step*Math.SQRT2/2);}
 const xy=(i:number):Point=>[ox+(i%w+.5)*step,oy+(Math.floor(i/w)+.5)*step];const index=(p:Point)=>{const x=Math.floor((p[0]-ox)/step),y=Math.floor((p[1]-oy)/step);return x>=0&&y>=0&&x<w&&y<h?y*w+x:-1;};
 const snap=(p:Point)=>{if(!pointInMulti(p,input.free))return -1;const i=index(p);if(i>=0&&open[i])return i;let best=-1,dd=Infinity;for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++){const q:Point=[p[0]+x*step,p[1]+y*step],j=index(q);if(j>=0&&open[j]){const d=Math.hypot(...[q[0]-p[0],q[1]-p[1]]);if(d<dd&&pointInMulti([(p[0]+q[0])/2,(p[1]+q[1])/2],input.free)){best=j;dd=d;}}}return best;};
 const autoGoal=(box:NonNullable<RouteRequest['targetBox']>)=>{let best=-1,max=-1;const x0=Math.max(1,Math.floor((box.x-ox)/step)),x1=Math.min(w-2,Math.ceil((box.x+box.w-ox)/step)),y0=Math.max(1,Math.floor((box.y-oy)/step)),y1=Math.min(h-2,Math.ceil((box.y+box.h-oy)/step));for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const i=y*w+x;if(open[i]&&field[i]>max){best=i;max=field[i];}}return best;};
 const cache=new Map<number,{cap:Float32Array;prev:Int32Array}>();
 function search(start:number){if(cache.has(start))return cache.get(start)!;const cap=new Float32Array(N),prev=new Int32Array(N),done=new Uint8Array(N),heap=new Heap();prev.fill(-1);cap[start]=field[start];heap.push(start,cap[start]);while(heap.ids.length){const [u]=heap.pop();if(done[u])continue;done[u]=1;const x=u%w,y=Math.floor(u/w);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy||x+dx<1||x+dx>=w-1||y+dy<1||y+dy>=h-1)continue;const j=u+dy*w+dx;if(!open[j]||done[j])continue;let value=Math.min(cap[u],field[j]);if(dx&&dy){const a=u+dx,c=u+dy*w;if(!open[a]||!open[c])continue;value=Math.min(value,field[a],field[c]);}if(value>cap[j]+.001){cap[j]=value;prev[j]=u;heap.push(j,value);}}}const result={cap,prev};if(cache.size>=2)cache.clear();cache.set(start,result);return result;}
 function shortest(start:number,end:number,radius:number){const cost=new Float32Array(N);cost.fill(Infinity);const prev=new Int32Array(N);prev.fill(-1);const heap=new Heap();cost[start]=0;heap.push(start,0);while(heap.ids.length){const [u]=heap.pop();if(u===end)break;const x=u%w,y=Math.floor(u/w);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy||x+dx<1||x+dx>=w-1||y+dy<1||y+dy>=h-1)continue;const j=u+dy*w+dx;if(field[j]+.001<radius||!open[j]||dx&&dy&&(field[u+dx]+.001<radius||field[u+dy*w]+.001<radius||!open[u+dx]||!open[u+dy*w]))continue;const c=cost[u]+(dx&&dy?Math.SQRT2:1);if(c+1e-4<cost[j]){cost[j]=c;prev[j]=u;const ex=end%w-(x+dx),ey=Math.floor(end/w)-(y+dy);heap.push(j,-c-Math.hypot(ex,ey));}}}return prev;}
 const results:RouteResult[]=[];for(const req of input.requests){const result:RouteResult={id:req.id,name:req.name,points:[],width:null,target:req.target,length:0,status:'invalid',note:'起点或终点不在可行走区域，请调整端点。',resolution:step};const ids=req.points.map(snap);if(req.targetBox&&ids.length)ids[ids.length-1]=autoGoal(req.targetBox);if(ids.some(i=>i<0)||ids.length<2){results.push(result);continue;}let route:number[]=[],min=Infinity,failed=false;
  for(let k=1;k<ids.length;k++){const start=ids[k-1],end=ids[k],s=search(start);if(start!==end&&s.cap[end]<=0){failed=true;break;}const threshold=req.target===0?Math.min(450,s.cap[end]||field[end]):Math.min(req.target/2,s.cap[end]||field[end]),prev=shortest(start,end,threshold),part:number[]=[];let i=end,guard=0;while(i!==start&&i>=0&&guard++<N){part.push(i);i=prev[i];}if(i!==start){failed=true;break;}part.push(start);part.reverse();route.push(...(k>1?part.slice(1):part));}
  if(failed){results.push({...result,status:'blocked',note:'未找到连通路线；请检查门洞、家具或途经点。'});continue;}let bottleneck=route[0];for(const i of route)if(field[i]<min){min=field[i];bottleneck=i;}const pts:Point[]=[];for(let k=0;k<route.length;k++){const p=xy(route[k]);if(k>0){const q=xy(route[k-1]);result.length+=Math.hypot(p[0]-q[0],p[1]-q[1]);}if(k===0||k===route.length-1||route[k]-route[k-1]!==route[k+1]-route[k])pts.push(p);}
  const width=Math.max(0,2*min),status=req.target===0?'unrated':width>=req.target?'ok':req.target-width<=step*4?'borderline':'narrow';results.push({...result,points:pts,bottleneck:xy(bottleneck),width,status,note:status==='unrated'?'目标比较已关闭；仅报告通行包络估算，不判定是否舒适。':status==='borderline'?'接近目标，栅格保守估算；请核对对应净距。':status==='narrow'?'通行包络小于设定目标；可继续调整方案。':'按可移动圆形包络估算，非规范认证。'});
 }
 return {requestId:input.requestId,floorId:input.floorId,results,resolution:step,coarseOnly:step!==input.resolution};
}

export function annotateRouteUse(floor:Floor,route:RouteResult):RouteResult{
 const zones=floor.pieces.filter(p=>p.type==='zone'&&/儿童|爬|玩/.test(p.name)&&p.visible!==false);
 const crossed=zones.filter(p=>{const w=p.baseW||p.w,h=p.baseH||p.h,ring:Ring=([[0,0],[w,0],[w,h],[0,h]] as Point[]).map(q=>toWorld(p,q));return route.points.some(q=>pointInRing(q,ring))||route.points.slice(1).some((b,i)=>edges(ring).some(([c,d])=>segmentsIntersect(route.points[i],b,c,d)));});
 return crossed.length?{...route,note:route.note+' 路线经过'+crossed.map(p=>p.name).join('、')+'，需考虑玩耍占用。'}:route;
}
